//for authenticatiob and authorization
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP = "SIGN_UP";

//for category resources
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";

// for user resources
export const CREATE_USER = "CREATE_USER";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER = "FETCH_USER";
export const DELETE_USER = "DELETE_USER";
export const EDIT_USER = "EDIT_USER";

// for city resources
export const CREATE_CITY = "CREATE_CITY";
export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CITY = "FETCH_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const EDIT_CITY = "EDIT_CITY";

// for vendor resources
export const CREATE_VENDOR = "CREATE_VENDOR";
export const FETCH_VENDORS = "FETCH_VENDORS";
export const FETCH_VENDOR = "FETCH_VENDOR";
export const DELETE_VENDOR = "DELETE_VENDOR";
export const EDIT_VENDOR = "EDIT_VENDOR";

// for product resources
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";

// for policy resources
export const CREATE_POLICY = "CREATE_POLICY";
export const FETCH_POLICIES = "FETCH_POLICIES";
export const FETCH_POLICY = "FETCH_POLICY";
export const DELETE_POLICY = "DELETE_POLICY";
export const EDIT_POLICY = "EDIT_POLICY";

// for countries resources
export const CREATE_COUNTRY = "CREATE_COUNTRY";
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const EDIT_COUNTRY = "EDIT_COUNTRY";

// for state resources
export const CREATE_STATE = "CREATE_STATE";
export const FETCH_STATES = "FETCH_STATES";
export const FETCH_STATE = "FETCH_STATE";
export const DELETE_STATE = "DELETE_STATE";
export const EDIT_STATE = "EDIT_STATE";

// for currency resources
export const CREATE_CURRENCY = "CREATE_CURRENCY";
export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const FETCH_CURRENCY = "FETCH_CURRENCY";
export const DELETE_CURRENCY = "DELETE_CURRENCY";
export const EDIT_CURRENCY = "EDIT_CURRENCY";

// for Scheme Codes
export const CREATE_SCHEMECODE = "CREATE_SCHEMECODE";
export const FETCH_SCHEMECODES = "FETCH_SCHEMECODES";
export const FETCH_SCHEMECODE = "FETCH_SCHEMECODE";
export const DELETE_SCHEMECODE = "DELETE_SCHEMECODE";
export const EDIT_SCHEMECODE = "EDIT_SCHEMECODE";

// for General Ledger Codes
export const CREATE_GLCODE = "CREATE_GLCODE";
export const FETCH_GLCODES = "FETCH_GLCODES";
export const FETCH_GLCODE = "FETCH_GLCODE";
export const DELETE_GLCODE = "DELETE_GLCODE";
export const EDIT_GLCODE = "EDIT_GLCODE";

// for General Subsidiar Ledger Codes
export const CREATE_SUBGLCODE = "CREATE_SUBGLCODE";
export const FETCH_SUBGLCODES = "FETCH_SUBGLCODES";
export const FETCH_SUBGLCODE = "FETCH_SUBGLCODE";
export const DELETE_SUBGLCODE = "DELETE_SUBGLCODE";
export const EDIT_GLSUBCODE = "EDIT_GLSUBCODE";

// for Transaction types
export const CREATE_TRANSTYPE = "CREATE_TRANSTYPE";
export const FETCH_TRANSTYPES = "FETCH_TRANSTYPES";
export const FETCH_TRANSTYPE = "FETCH_TRANSTYPE";
export const DELETE_TRANSTYPE = "DELETE_TRANSTYPE";
export const EDIT_TRANSTYPE = "EDIT_TRANSTYPE";

// for Service Outlets
export const CREATE_SERVICEOUTLET = "CREATE_SERVICEOUTLET";
export const FETCH_SERVICEOUTLETS = "FETCH_SERVICEOUTLETS";
export const FETCH_SERVICEOUTLET = "FETCH_SERVICEOUTLET";
export const DELETE_SERVICEOUTLET = "DELETE_SERVICEOUTLET";
export const EDIT_SERVICEOUTLET = "EDIT_SERVICEOUTLET";

// for Locations
export const CREATE_LOCATION = "CREATE_LOCATION";
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const FETCH_LOCATION = "FETCH_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const EDIT_LOCATION_SUCCEEDED = "EDIT_LOCATION_SUCCEEDED";
export const EDIT_LOCATION_FAILED = "EDIT_LOCATION_FAILED";

// for Headoffice Service Outlets
export const CREATE_HOSERVICEOUTLET = "CREATE_HOSERVICEOUTLET";
export const FETCH_HOSERVICEOUTLETS = "FETCH_HOSERVICEOUTLETS";
export const FETCH_HOSERVICEOUTLET = "FETCH_HOSERVICEOUTLET";
export const DELETE_HOSERVICEOUTLET = "DELETE_HOSERVICEOUTLET";
export const EDIT_HOSERVICEOUTLET = "EDIT_HOSERVICEOUTLET";

// for Office Operations and Services
export const CREATE_OFFICEOPERATION = "CREATE_OFFICEOPERATION";
export const FETCH_OFFICEOPERATIONS = "FETCH_OFFICEOPERATIONS";
export const FETCH_OFFICEOPERATION = "FETCH_OFFICEOPERATION";
export const DELETE_OFFICEOPERATION = "DELETE_OFFICEOPERATION";
export const EDIT_OFFICEOPERATION = "EDIT_OFFICEOPERATION";

// for asset store types
export const CREATE_STORETYPE = "CREATE_STORETYPE";
export const FETCH_STORETYPES = "FETCH_STORETYPES";
export const FETCH_STORETYPE = "FETCH_STORETYPE";
export const DELETE_STORETYPE = "DELETE_STORETYPE";
export const EDIT_STORETYPE = "EDIT_STORETYPE";

// for asset subclasses
export const CREATE_SUBCLASS = "CREATE_SUBCLASS";
export const FETCH_SUBCLASSES = "FETCH_SUBCLASSES";
export const FETCH_SUBCLASS = "FETCH_SUBCLASS";
export const DELETE_SUBCLASS = "DELETE_SUBCLASS";
export const EDIT_SUBCLASS = "EDIT_SUBCLASS";

// for asset asset types
export const CREATE_ASSETTYPE = "CREATE_ASSETTYPE";
export const FETCH_ASSETTYPES = "FETCH_ASSETTYPES";
export const FETCH_ASSETTYPE = "FETCH_ASSETTYPE";
export const DELETE_ASSETTYPE = "DELETE_ASSETTYPE";
export const EDIT_ASSETTYPE = "EDIT_ASSETTYPE";

// for asset depreciation types
export const CREATE_DEPRECIATIONTYPE = "CREATE_DEPRECIATIONTYPE";
export const FETCH_DEPRECIATIONTYPES = "FETCH_DEPRECIATIONTYPES";
export const FETCH_DEPRECIATIONTYPE = "FETCH_DEPRECIATIONTYPE";
export const DELETE_DEPRECIATIONTYPE = "DELETE_DEPRECIATIONTYPE";
export const EDIT_DEPRECIATIONTYPE = "EDIT_DEPRECIATIONTYPE";

// for asset maintenance types
export const CREATE_MAINTENANCETYPE = "CREATE_MAINTENANCETYPE";
export const FETCH_MAINTENANCETYPES = "FETCH_MAINTENANCETYPES";
export const FETCH_MAINTENANCETYPE = "FETCH_MAINTENANCETYPE";
export const DELETE_MAINTENANCETYPE = "DELETE_MAINTENANCETYPE";
export const EDIT_MAINTENANCETYPE = "EDIT_MAINTENANCETYPE";

// for asset measurement units
export const CREATE_MEASUREMENTUNIT = "CREATE_MEASUREMENTUNIT";
export const FETCH_MEASUREMENTUNITS = "FETCH_MEASUREMENTUNITS";
export const FETCH_MEASUREMENTUNIT = "FETCH_MEASUREMENTUNIT";
export const DELETE_MEASUREMENTUNIT = "DELETE_MEASUREMENTUNIT";
export const EDIT_MEASUREMENTUNIT = "EDIT_MEASUREMENTUNIT";

// for asset and stocks
export const CREATE_STOCK = "CREATE_STOCK";
export const FETCH_STOCKS = "FETCH_STOCKS";
export const FETCH_STOCK = "FETCH_STOCK";
export const DELETE_STOCK = "DELETE_STOCK";
export const EDIT_STOCK = "EDIT_STOCK";

// for other assets
export const CREATE_OTHERASSET = "CREATE_OTHERASSET";
export const FETCH_OTHERASSETS = "FETCH_OTHERASSETS";
export const FETCH_OTHERASSET = "FETCH_OTHERASSET";
export const DELETE_OTHERASSET = "DELETE_OTHERASSET";
export const EDIT_OTHERASSET = "EDIT_OTHERASSET";

// for unapproved procurement actions
export const CREATE_UNAPPROVEDPROCUREMENT = "CREATE_UNAPPROVEDPROCUREMENT";
export const FETCH_UNAPPROVEDPROCUREMENTS = "FETCH_UNAPPROVEDPROCUREMENTS";
export const FETCH_UNAPPROVEDPROCUREMENT = "FETCH_UNAPPROVEDPROCUREMENT";
export const DELETE_UNAPPROVEDPROCUREMENT = "DELETE_UNAPPROVEDPROCUREMENT";
export const EDIT_UNAPPROVEDPROCUREMENT = "EDIT_UNAPPROVEDPROCUREMENT";

// for approved procurement actions
export const CREATE_APPROVEDPROCUREMENT = "CREATE_APPROVEDPROCUREMENT";
export const FETCH_APPROVEDPROCUREMENTS = "FETCH_APPROVEDPROCUREMENTS";
export const FETCH_APPROVEDPROCUREMENT = "FETCH_APPROVEDPROCUREMENT";
export const DELETE_APPROVEDPROCUREMENT = "DELETE_APPROVEDPROCUREMENT";
export const EDIT_APPROVEDPROCUREMENT = "EDIT_APPROVEDPROCUREMENT";

// for executed procurement actions
export const CREATE_EXECAPPROVEDPROCUREMENT = "CREATE_EXECAPPROVEDPROCUREMENT";
export const FETCH_EXECAPPROVEDPROCUREMENTS = "FETCH_EXECAPPROVEDPROCUREMENTS";
export const FETCH_EXECAPPROVEDPROCUREMENT = "FETCH_EXECAPPROVEDPROCUREMENT";
export const DELETE_EXECAPPROVEDPROCUREMENT = "DELETE_EXECAPPROVEDPROCUREMENT";
export const EDIT_EXECAPPROVEDPROCUREMENT = "EDIT_EXECAPPROVEDPROCUREMENT";

// for unapproved maintenance action types
export const CREATE_UNAPPROVEDMAINTENANCE = "CREATE_UNAPPROVEDMAINTENANCE";
export const FETCH_UNAPPROVEDMAINTENANCES = "FETCH_UNAPPROVEDMAINTENANCES";
export const FETCH_UNAPPROVEDMAINTENANCE = "FETCH_UNAPPROVEDMAINTENANCE";
export const DELETE_UNAPPROVEDMAINTENANCE = "DELETE_UNAPPROVEDMAINTENANCE";
export const EDIT_UNAPPROVEDMAINTENANCE = "EDIT_UNAPPROVEDMAINTENANCE";

// for approved maintenance action types
export const CREATE_APPROVEDMAINTENANCE = "CREATE_APPROVEDMAINTENANCE";
export const FETCH_APPROVEDMAINTENANCES = "FETCH_APPROVEDMAINTENANCES";
export const FETCH_APPROVEDMAINTENANCE = "FETCH_APPROVEDMAINTENANCE";
export const DELETE_APPROVEDMAINTENANCE = "DELETE_APPROVEDMAINTENANCE";
export const EDIT_APPROVEDMAINTENANCE = "EDIT_APPROVEDMAINTENANCE";

// for executed maintenance action types
export const CREATE_EXECUTEDMAINTENANCE = "CREATE_EXECUTEDMAINTENANCE";
export const FETCH_EXECUTEDMAINTENANCES = "FETCH_EXECUTEDMAINTENANCES";
export const FETCH_EXECUTEDMAINTENANCE = "FETCH_EXECUTEDMAINTENANCE";
export const DELETE_EXECUTEDMAINTENANCE = "DELETE_EXECUTEDMAINTENANCE";
export const EDIT_EXECUTEDMAINTENANCE = "EDIT_EXECUTEDMAINTENANCE";

// for asset inventory action types
export const MAKE_INVENTORYREQUISITIONREQUEST =
  "MAKE_INVENTORYREQUISITIONREQUEST";
export const MAKE_INVENTORYDISPOSALREQUEST = "MAKE_INVENTORYDISPOSALREQUEST";
export const MAKE_INVENTORYRETIREMENTREQUEST =
  "MAKE_INVENTORYRETIREMENTREQUEST";
export const MAKE_INVENTORYTRANSFERREQUEST = "MAKE_INVENTORYTRANSFERREQUEST";
export const FETCH_INVENTORYSTOCKS = "FETCH_INVENTORYSTOCKS";
export const FETCH_INVENTORYSTOCK = "FETCH_INVENTORYSTOCK";
export const DELETE_INVENTORYSTOCK = "DELETE_INVENTORYSTOCK";
export const EDIT_INVENTORYSTOCK = "EDIT_INVENTORYSTOCK";

// for unapproved requisition action types
export const FETCH_UNAPPROVEDSTOCKREQUISITIONS =
  "FETCH_UNAPPROVEDSTOCKREQUISITIONS";
export const FETCH_UNAPPROVEDSTOCKREQUISITION =
  "FETCH_UNAPPROVEDSTOCKREQUISITION";
export const DELETE_UNAPPROVEDSTOCKREQUISITION =
  "DELETE_UNAPPROVEDSTOCKREQUISITION";
export const EDIT_UNAPPROVEDSTOCKREQUISITION =
  "EDIT_UNAPPROVEDSTOCKREQUISITION";

// for unapproved retirement action types
export const FETCH_UNAPPROVEDSTOCKRETIREMENTS =
  "FETCH_UNAPPROVEDSTOCKRETIREMENTS";
export const FETCH_UNAPPROVEDSTOCKRETIREMENT =
  "FETCH_UNAPPROVEDSTOCKRETIREMENT";
export const DELETE_UNAPPROVEDSTOCKRETIREMENT =
  "DELETE_UNAPPROVEDSTOCKRETIREMENT";
export const EDIT_UNAPPROVEDSTOCKRETIREMENT = "EDIT_UNAPPROVEDSTOCKRETIREMENT";

// for unapproved disposal action types
export const FETCH_UNAPPROVEDSTOCKDISPOSITIONS =
  "FETCH_UNAPPROVEDSTOCKDISPOSITIONS";
export const FETCH_UNAPPROVEDSTOCKDISPOSITION =
  "FETCH_UNAPPROVEDSTOCKDISPOSITION";
export const DELETE_UNAPPROVEDSTOCKDISPOSITION =
  "DELETE_UNAPPROVEDSTOCKDISPOSITION";
export const EDIT_UNAPPROVEDSTOCKDISPOSITION =
  "EDIT_UNAPPROVEDSTOCKDISPOSITION";

// for unapproved transfers & lease action types
export const FETCH_UNAPPROVEDSTOCKTRANSFERS = "FETCH_UNAPPROVEDSTOCKTRANSFERS";
export const FETCH_UNAPPROVEDSTOCKTRANSFER = "FETCH_UNAPPROVEDSTOCKTRANSFER";
export const DELETE_UNAPPROVEDSTOCKTRANSFER = "DELETE_UNAPPROVEDSTOCKTRANSFER";
export const EDIT_UNAPPROVEDSTOCKTRANSFER = "EDIT_UNAPPROVEDSTOCKTRANSFER";

// for asset requisition action types
export const FETCH_ASSETREQUISITIONS = "FETCH_ASSETREQUISITIONS";
export const FETCH_ASSETREQUISITION = "FETCH_ASSETREQUISITION";
export const DELETE_ASSETREQUISITION = "DELETE_ASSETREQUISITION";
export const EDIT_ASSETREQUISITION = "EDIT_ASSETREQUISITION";

// for asset pending quisition action types
export const FETCH_PENDINGASSETREQUISITIONS = "FETCH_PENDINGASSETREQUISITIONS";
export const FETCH_PENDINGASSETREQUISITION = "FETCH_PENDINGASSETREQUISITION";
export const DELETE_PENDINGASSETREQUISITION = "DELETE_PENDINGASSETREQUISITION";
export const EDIT_PENDINGASSETREQUISITION = "EDIT_PENDINGASSETREQUISITION";

// for asset withdrawn requisition action types
export const FETCH_WITHDRAWNASSETREQUISITIONS =
  "FETCH_WITHDRAWNASSETREQUISITIONS";
export const FETCH_WITHDRAWNASSETREQUISITION =
  "FETCH_WITHDRAWNASSETREQUISITION";
export const DELETE_WITHDRAWNASSETREQUISITION =
  "DELETE_WITHDRAWNASSETREQUISITION";
export const EDIT_WITHDRAWNASSETREQUISITION = "EDIT_WITHDRAWNASSETREQUISITION";

// for asset aborted requisition action types
export const FETCH_ABORTEDASSETREQUISITIONS = "FETCH_ABORTEDASSETREQUISITIONS";
export const FETCH_ABORTEDASSETREQUISITION = "FETCH_ABORTEDASSETREQUISITION";
export const DELETE_ABORTEDASSETREQUISITION = "DELETE_ABORTEDASSETREQUISITION";
export const EDIT_ABORTEDASSETREQUISITION = "EDIT_ABORTEDASSETREQUISITION";

// for asset returns post requisition action types
export const FETCH_RETURNASSETPOSTREQUISITIONS =
  "FETCH_RETURNASSETPOSTREQUISITIONS";
export const FETCH_RETURNASSETPOSTREQUISITION =
  "FETCH_RETURNASSETPOSTREQUISITION";
export const DELETE_RETURNASSETPOSTREQUISITION =
  "DELETE_RETURNASSETPOSTREQUISITION";
export const EDIT_RETURNASSETPOSTREQUISITION =
  "EDIT_RETURNASSETPOSTREQUISITION";

// for asset retirement action types
export const FETCH_ASSETRETIREMENTS = "FETCH_ASSETRETIREMENTS";
export const FETCH_ASSETRETIREMENT = "FETCH_ASSETRETIREMENT";
export const DELETE_ASSETRETIREMENT = "DELETE_ASSETRETIREMENT";
export const EDIT_ASSETRETIREMENT = "EDIT_ASSETRETIREMENT";

// for asset pending retirement action types
export const FETCH_PENDINGASSETRETIREMENTS = "FETCH_PENDINGASSETRETIREMENTS";
export const FETCH_PENDINGASSETRETIREMENT = "FETCH_PENDINGASSETRETIREMENT";
export const DELETE_PENDINGASSETRETIREMENT = "DELETE_PENDINGASSETRETIREMENT";
export const EDIT_PENDINGASSETRETIREMENT = "EDIT_PENDINGASSETRETIREMENT";

// for asset withdrawn retirement action types
export const FETCH_WITHDRAWNASSETRETIREMENTS =
  "FETCH_WITHDRAWNASSETRETIREMENTS";
export const FETCH_WITHDRAWNASSETRETIREMENT = "FETCH_WITHDRAWNASSETRETIREMENT";
export const DELETE_WITHDRAWNASSETRETIREMENT =
  "DELETE_WITHDRAWNASSETRETIREMENT";
export const EDIT_WITHDRAWNASSETRETIREMENT = "EDIT_WITHDRAWNASSETRETIREMENT";

// for asset return post  retirement action types
export const FETCH_RETURNPOSTASSETRETIREMENTS =
  "FETCH_RETURNPOSTASSETRETIREMENTS";
export const FETCH_RETURNPOSTASSETRETIREMENT =
  "FETCH_RETURNPOSTASSETRETIREMENT";
export const DELETE_RETURNPOSTASSETRETIREMENT =
  "DELETE_RETURNPOSTASSETRETIREMENT";
export const EDIT_RETURNPOSTASSETRETIREMENT = "EDIT_RETURNPOSTASSETRETIREMENT";

// for asset dispositions action types
export const FETCH_ASSETDISPOSITIONS = "FETCH_ASSETDISPOSITIONS";
export const FETCH_ASSETDISPOSITION = "FETCH_ASSETDISPOSITION";
export const DELETE_ASSETDISPOSITION = "DELETE_ASSETDISPOSITION";
export const EDIT_ASSETDISPOSITION = "EDIT_ASSETDISPOSITION";

// for asset pending dispositions action types
export const FETCH_PENDINGASSETDISPOSITIONS = "FETCH_PENDINGASSETDISPOSITIONS";
export const FETCH_PENDINGASSETDISPOSITION = "FETCH_PENDINGASSETDISPOSITION";
export const DELETE_PENDINGASSETDISPOSITION = "DELETE_PENDINGASSETDISPOSITION";
export const EDIT_PENDINGASSETDISPOSITION = "EDIT_PENDINGASSETDISPOSITION";

// for asset withdrawn dispositions action types
export const FETCH_WITHDRAWNASSETDISPOSITIONS =
  "FETCH_WITHDRAWNASSETDISPOSITIONS";
export const FETCH_WITHDRAWNASSETDISPOSITION =
  "FETCH_WITHDRAWNASSETDISPOSITION";
export const DELETE_WITHDRAWNASSETDISPOSITION =
  "DELETE_WITHDRAWNASSETDISPOSITION";
export const EDIT_WITHDRAWNASSETDISPOSITION = "EDIT_WITHDRAWNASSETDISPOSITION";

// for return asset post dispositions action types
export const FETCH_RETURNASSETPOSTDISPOSITIONS =
  "FETCH_RETURNASSETPOSTDISPOSITIONS";
export const FETCH_RETURNASSETPOSTDISPOSITION =
  "FETCH_RETURNASSETPOSTDISPOSITION";
export const DELETE_RETURNASSETPOSTDISPOSITION =
  "DELETE_RETURNASSETPOSTDISPOSITION";
export const EDIT_RETURNASSETPOSTDISPOSITION =
  "EDIT_RETURNASSETPOSTDISPOSITION";

// for asset movements action types
export const CREATE_ASSETMOVEMENT = "CREATE_ASSETMOVEMENT";
export const FETCH_ASSETMOVEMENTS = "FETCH_ASSETMOVEMENTS";
export const FETCH_ASSETMOVEMENT = "FETCH_ASSETMOVEMENT";
export const DELETE_ASSETMOVEMENT = "DELETE_ASSETMOVEMENT";
export const EDIT_ASSETMOVEMENT = "EDIT_ASSETMOVEMENT";

// for asset transfer movements action types
export const CREATE_TRANSFERASSETMOVEMENT = "CREATE_TRANSFERASSETMOVEMENT";
export const FETCH_TRANSFERASSETMOVEMENTS = "FETCH_TRANSFERASSETMOVEMENTS";
export const FETCH_TRANSFERASSETMOVEMENT = "FETCH_TRANSFERASSETMOVEMENT";
export const DELETE_TRANSFERASSETMOVEMENT = "DELETE_TRANSFERASSETMOVEMENT";
export const EDIT_TRANSFERASSETMOVEMENT = "EDIT_TRANSFERASSETMOVEMENT";

// for asset pending transfer movements action types
export const CREATE_PENDINGTRANSFERASSETMOVEMENT =
  "CREATE_PENDINGTRANSFERASSETMOVEMENT";
export const FETCH_PENDINGTRANSFERASSETMOVEMENTS =
  "FETCH_PENDINGTRANSFERASSETMOVEMENTS";
export const FETCH_PENDINGTRANSFERASSETMOVEMENT =
  "FETCH_PENDINGTRANSFERASSETMOVEMENT";
export const DELETE_PENDINGTRANSFERASSETMOVEMENT =
  "DELETE_PENDINGTRANSFERASSETMOVEMENT";
export const EDIT_PENDINGTRANSFERASSETMOVEMENT =
  "EDIT_PENDINGTRANSFERASSETMOVEMENT";

// for asset WITHDRAWN transfer movements action types
export const CREATE_WITHDRAWNTRANSFERASSETMOVEMENT =
  "CREATE_WITHDRAWNTRANSFERASSETMOVEMENT";
export const FETCH_WITHDRAWNTRANSFERASSETMOVEMENTS =
  "FETCH_WITHDRAWNTRANSFERASSETMOVEMENTS";
export const FETCH_WITHDRAWNTRANSFERASSETMOVEMENT =
  "FETCH_WITHDRAWNTRANSFERASSETMOVEMENT";
export const DELETE_WITHDRAWNTRANSFERASSETMOVEMENT =
  "DELETE_WITHDRAWNTRANSFERASSETMOVEMENT";
export const EDIT_WITHDRAWNTRANSFERASSETMOVEMENT =
  "EDIT_WITHDRAWNTRANSFERASSETMOVEMENT";

// for asset returned transfer movements action types
export const CREATE_RETURNASSETPOSTTRANSFERMOVEMENT =
  "CREATE_RETURNASSETPOSTTRANSFERMOVEMENT";
export const FETCH_RETURNASSETPOSTTRANSFERMOVEMENTS =
  "FETCH_RETURNASSETPOSTTRANSFERMOVEMENTS";
export const FETCH_RETURNASSETPOSTTRANSFERMOVEMENT =
  "FETCH_RETURNASSETPOSTTRANSFERMOVEMENT";
export const DELETE_RETURNASSETPOSTTRANSFERMOVEMENT =
  "DELETE_RETURNASSETPOSTTRANSFERMOVEMENT";
export const EDIT_RETURNASSETPOSTTRANSERMOVEMENT =
  "EDIT_RETURNASSETPOSTTRANSERMOVEMENT";

// for asset store action types
export const CREATE_ASSETSTORE = "CREATE_ASSETSTORE";
export const FETCH_ASSETSTORES = "FETCH_ASSETSTORES";
export const FETCH_ASSETSTORE = "FETCH_ASSETSTORE";
export const DELETE_ASSETSTORE = "DELETE_ASSETSTORE";
export const EDIT_ASSETSTORE = "EDIT_ASSETSTORE";

// for asset store maintenance  action types
export const CREATE_MAINTENANCEASSETSTORE = "CREATE_MAINTENANCEASSETSTORE";
export const FETCH_MAINTENANCEASSETSTORES = "FETCH_MAINTENANCEASSETSTORES";
export const FETCH_MAINTENANCEASSETSTORE = "FETCH_MAINTENANCEASSETSTORE";
export const DELETE_MAINTENANCEASSETSTORE = "DELETE_MAINTENANCEASSETSTORE";
export const EDIT_MAINTENANCEASSETSTORE = "EDIT_MAINTENANCEASSETSTORE";

// for asset store lease  action types
export const CREATE_LEASEASSETSTORE = "CREATE_LEASEASSETSTORE";
export const FETCH_LEASEASSETSTORES = "FETCH_LEASEASSETSTORES";
export const FETCH_LEASEASSETSTORE = "FETCH_LEASEASSETSTORE";
export const DELETE_LEASEASSETSTORE = "DELETE_LEASEASSETSTORE";
export const EDIT_LEASEASSETSTORE = "EDIT_LEASEASSETSTORE";

// for asset store ownership  action types
export const CREATE_OWNERSHIPASSETSTORE = "CREATE_OWNERSHIPASSETSTORE";
export const FETCH_OWNERSHIPASSETSTORES = "FETCH_OWNERSHIPASSETSTORES";
export const FETCH_OWNERSHIPASSETSTORE = "FETCH_OWNERSHIPASSETSTORE";
export const DELETE_OWNERSHIPASSETSTORE = "DELETE_OWNERSHIPASSETSTORE";
export const EDIT_OWNERSHIPASSETSTORE = "EDIT_OWNERSHIPASSETSTORE";

// for asset store space allocation  action types
export const CREATE_ASSETSTORESPACEALLOCATION =
  "CREATE_ASSETSTORESPACEALLOCATION";
export const FETCH_ASSETSTORESPACEALLOCATIONS =
  "FETCH_ASSETSTORESPACEALLOCATIONS";
export const FETCH_ASSETSTORESPACEALLOCATION =
  "FETCH_ASSETSTORESPACEALLOCATION";
export const DELETE_ASSETSTORESPACEALLOCATION =
  "DELETE_ASSETSTORESPACEALLOCATION";
export const EDIT_ASSETSTORESPACEALLOCATION = "EDIT_ASSETSTORESPACEALLOCATION";

// for asset store sell  action types
export const CREATE_SELLASSETSTORE = "CREATE_SELLASSETSTORE";
export const FETCH_SELLASSETSTORES = "FETCH_SELLASSETSTORES";
export const FETCH_SELLASSETSTORE = "FETCH_SELLASSETSTORE";
export const DELETE_SELLASSETSTORE = "DELETE_SELLASSETSTORE";
export const EDIT_SELLASSETSTORE = "EDIT_SELLASSETSTORE";

// for asset store closure  action types
export const CREATE_ASSETSTORECLOSURE = "CREATE_ASSETSTORECLOSURE";
export const FETCH_ASSETSTORECLOSURES = "FETCH_ASSETSTORECLOSURES";
export const FETCH_ASSETSTORECLOSURE = "FETCH_ASSETSTORECLOSURE";
export const DELETE_ASSETSTORECLOSURE = "DELETE_ASSETSTORECLOSURE";
export const EDIT_ASSETSTORECLOSURE = "EDIT_ASSETSTORECLOSURE";
