//for authenticatiob and authorization
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP = "SIGN_UP";

//for category resources
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";

// for user resources
export const CREATE_USER = "CREATE_USER";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER = "FETCH_USER";
export const DELETE_USER = "DELETE_USER";
export const EDIT_USER = "EDIT_USER";

// for city resources
export const CREATE_CITY = "CREATE_CITY";
export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CITY = "FETCH_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const EDIT_CITY = "EDIT_CITY";

// for vendor resources
export const CREATE_VENDOR = "CREATE_VENDOR";
export const FETCH_VENDORS = "FETCH_VENDORS";
export const FETCH_VENDOR = "FETCH_VENDOR";
export const DELETE_VENDOR = "DELETE_VENDOR";
export const EDIT_VENDOR = "EDIT_VENDOR";

// for product resources
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";

// for policy resources
export const CREATE_POLICY = "CREATE_POLICY";
export const FETCH_POLICIES = "FETCH_POLICIES";
export const FETCH_POLICY = "FETCH_POLICY";
export const DELETE_POLICY = "DELETE_POLICY";
export const EDIT_POLICY = "EDIT_POLICY";

// for countries resources
export const CREATE_COUNTRY = "CREATE_COUNTRY";
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const EDIT_COUNTRY = "EDIT_COUNTRY";

// for state resources
export const CREATE_STATE = "CREATE_STATE";
export const FETCH_STATES = "FETCH_STATES";
export const FETCH_STATE = "FETCH_STATE";
export const DELETE_STATE = "DELETE_STATE";
export const EDIT_STATE = "EDIT_STATE";

// for currency resources
export const CREATE_CURRENCY = "CREATE_CURRENCY";
export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const FETCH_CURRENCY = "FETCH_CURRENCY";
export const DELETE_CURRENCY = "DELETE_CURRENCY";
export const EDIT_CURRENCY = "EDIT_CURRENCY";

// for Scheme Codes
export const CREATE_SCHEMECODE = "CREATE_SCHEMECODE";
export const FETCH_SCHEMECODES = "FETCH_SCHEMECODES";
export const FETCH_SCHEMECODE = "FETCH_SCHEMECODE";
export const DELETE_SCHEMECODE = "DELETE_SCHEMECODE";
export const EDIT_SCHEMECODE = "EDIT_SCHEMECODE";

// for General Ledger Codes
export const CREATE_GLCODE = "CREATE_GLCODE";
export const FETCH_GLCODES = "FETCH_GLCODES";
export const FETCH_GLCODE = "FETCH_GLCODE";
export const DELETE_GLCODE = "DELETE_GLCODE";
export const EDIT_GLCODE = "EDIT_GLCODE";

// for General Subsidiar Ledger Codes
export const CREATE_SUBGLCODE = "CREATE_SUBGLCODE";
export const FETCH_SUBGLCODES = "FETCH_SUBGLCODES";
export const FETCH_SUBGLCODE = "FETCH_SUBGLCODE";
export const DELETE_SUBGLCODE = "DELETE_SUBGLCODE";
export const EDIT_GLSUBCODE = "EDIT_GLSUBCODE";

// for Transaction types
export const CREATE_TRANSTYPE = "CREATE_TRANSTYPE";
export const FETCH_TRANSTYPES = "FETCH_TRANSTYPES";
export const FETCH_TRANSTYPE = "FETCH_TRANSTYPE";
export const DELETE_TRANSTYPE = "DELETE_TRANSTYPE";
export const EDIT_TRANSTYPE = "EDIT_TRANSTYPE";

// for Service Outlets
export const CREATE_SERVICEOUTLET = "CREATE_SERVICEOUTLET";
export const FETCH_SERVICEOUTLETS = "FETCH_SERVICEOUTLETS";
export const FETCH_SERVICEOUTLET = "FETCH_SERVICEOUTLET";
export const DELETE_SERVICEOUTLET = "DELETE_SERVICEOUTLET";
export const EDIT_SERVICEOUTLET = "EDIT_SERVICEOUTLET";

// for Locations
export const CREATE_LOCATION = "CREATE_LOCATION";
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const FETCH_LOCATION = "FETCH_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const EDIT_LOCATION_SUCCEEDED = "EDIT_LOCATION_SUCCEEDED";
export const EDIT_LOCATION_FAILED = "EDIT_LOCATION_FAILED";

// for Headoffice Service Outlets
export const CREATE_HOSERVICEOUTLET = "CREATE_HOSERVICEOUTLET";
export const FETCH_HOSERVICEOUTLETS = "FETCH_HOSERVICEOUTLETS";
export const FETCH_HOSERVICEOUTLET = "FETCH_HOSERVICEOUTLET";
export const DELETE_HOSERVICEOUTLET = "DELETE_HOSERVICEOUTLET";
export const EDIT_HOSERVICEOUTLET = "EDIT_HOSERVICEOUTLET";

// for Office Operations and Services
export const CREATE_OFFICEOPERATION = "CREATE_OFFICEOPERATION";
export const FETCH_OFFICEOPERATIONS = "FETCH_OFFICEOPERATIONS";
export const FETCH_OFFICEOPERATION = "FETCH_OFFICEOPERATION";
export const DELETE_OFFICEOPERATION = "DELETE_OFFICEOPERATION";
export const EDIT_OFFICEOPERATION = "EDIT_OFFICEOPERATION";

// for asset store types
export const CREATE_STORETYPE = "CREATE_STORETYPE";
export const FETCH_STORETYPES = "FETCH_STORETYPES";
export const FETCH_STORETYPE = "FETCH_STORETYPE";
export const DELETE_STORETYPE = "DELETE_STORETYPE";
export const EDIT_STORETYPE = "EDIT_STORETYPE";

// for asset subclasses
export const CREATE_SUBCLASS = "CREATE_SUBCLASS";
export const FETCH_SUBCLASSES = "FETCH_SUBCLASSES";
export const FETCH_SUBCLASS = "FETCH_SUBCLASS";
export const DELETE_SUBCLASS = "DELETE_SUBCLASS";
export const EDIT_SUBCLASS = "EDIT_SUBCLASS";

// for asset asset types
export const CREATE_ASSETTYPE = "CREATE_ASSETTYPE";
export const FETCH_ASSETTYPES = "FETCH_ASSETTYPES";
export const FETCH_ASSETTYPE = "FETCH_ASSETTYPE";
export const DELETE_ASSETTYPE = "DELETE_ASSETTYPE";
export const EDIT_ASSETTYPE = "EDIT_ASSETTYPE";

// for asset depreciation types
export const CREATE_DEPRECIATIONTYPE = "CREATE_DEPRECIATIONTYPE";
export const FETCH_DEPRECIATIONTYPES = "FETCH_DEPRECIATIONTYPES";
export const FETCH_DEPRECIATIONTYPE = "FETCH_DEPRECIATIONTYPE";
export const DELETE_DEPRECIATIONTYPE = "DELETE_DEPRECIATIONTYPE";
export const EDIT_DEPRECIATIONTYPE = "EDIT_DEPRECIATIONTYPE";

// for asset maintenance types
export const CREATE_MAINTENANCETYPE = "CREATE_MAINTENANCETYPE";
export const FETCH_MAINTENANCETYPES = "FETCH_MAINTENANCETYPES";
export const FETCH_MAINTENANCETYPE = "FETCH_MAINTENANCETYPE";
export const DELETE_MAINTENANCETYPE = "DELETE_MAINTENANCETYPE";
export const EDIT_MAINTENANCETYPE = "EDIT_MAINTENANCETYPE";

// for asset measurement units
export const CREATE_MEASUREMENTUNIT = "CREATE_MEASUREMENTUNIT";
export const FETCH_MEASUREMENTUNITS = "FETCH_MEASUREMENTUNITS";
export const FETCH_MEASUREMENTUNIT = "FETCH_MEASUREMENTUNIT";
export const DELETE_MEASUREMENTUNIT = "DELETE_MEASUREMENTUNIT";
export const EDIT_MEASUREMENTUNIT = "EDIT_MEASUREMENTUNIT";

// for asset and stocks
export const CREATE_STOCK = "CREATE_STOCK";
export const FETCH_STOCKS = "FETCH_STOCKS";
export const FETCH_STOCK = "FETCH_STOCK";
export const DELETE_STOCK = "DELETE_STOCK";
export const EDIT_STOCK = "EDIT_STOCK";

// for other assets
export const CREATE_OTHERASSET = "CREATE_OTHERASSET";
export const FETCH_OTHERASSETS = "FETCH_OTHERASSETS";
export const FETCH_OTHERASSET = "FETCH_OTHERASSET";
export const DELETE_OTHERASSET = "DELETE_OTHERASSET";
export const EDIT_OTHERASSET = "EDIT_OTHERASSET";

// for unapproved procurement actions
export const CREATE_UNAPPROVEDPROCUREMENT = "CREATE_UNAPPROVEDPROCUREMENT";
export const FETCH_UNAPPROVEDPROCUREMENTS = "FETCH_UNAPPROVEDPROCUREMENTS";
export const FETCH_UNAPPROVEDPROCUREMENT = "FETCH_UNAPPROVEDPROCUREMENT";
export const DELETE_UNAPPROVEDPROCUREMENT = "DELETE_UNAPPROVEDPROCUREMENT";
export const EDIT_UNAPPROVEDPROCUREMENT = "EDIT_UNAPPROVEDPROCUREMENT";

// for approved procurement actions
export const CREATE_APPROVEDPROCUREMENT = "CREATE_APPROVEDPROCUREMENT";
export const FETCH_APPROVEDPROCUREMENTS = "FETCH_APPROVEDPROCUREMENTS";
export const FETCH_APPROVEDPROCUREMENT = "FETCH_APPROVEDPROCUREMENT";
export const DELETE_APPROVEDPROCUREMENT = "DELETE_APPROVEDPROCUREMENT";
export const EDIT_APPROVEDPROCUREMENT = "EDIT_APPROVEDPROCUREMENT";

// for executed procurement actions
export const CREATE_EXECAPPROVEDPROCUREMENT = "CREATE_EXECAPPROVEDPROCUREMENT";
export const FETCH_EXECAPPROVEDPROCUREMENTS = "FETCH_EXECAPPROVEDPROCUREMENTS";
export const FETCH_EXECAPPROVEDPROCUREMENT = "FETCH_EXECAPPROVEDPROCUREMENT";
export const DELETE_EXECAPPROVEDPROCUREMENT = "DELETE_EXECAPPROVEDPROCUREMENT";
export const EDIT_EXECAPPROVEDPROCUREMENT = "EDIT_EXECAPPROVEDPROCUREMENT";

// for unapproved maintenance action types
export const CREATE_UNAPPROVEDMAINTENANCE = "CREATE_UNAPPROVEDMAINTENANCE";
export const FETCH_UNAPPROVEDMAINTENANCES = "FETCH_UNAPPROVEDMAINTENANCES";
export const FETCH_UNAPPROVEDMAINTENANCE = "FETCH_UNAPPROVEDMAINTENANCE";
export const DELETE_UNAPPROVEDMAINTENANCE = "DELETE_UNAPPROVEDMAINTENANCE";
export const EDIT_UNAPPROVEDMAINTENANCE = "EDIT_UNAPPROVEDMAINTENANCE";

// for approved maintenance action types
export const CREATE_APPROVEDMAINTENANCE = "CREATE_APPROVEDMAINTENANCE";
export const FETCH_APPROVEDMAINTENANCES = "FETCH_APPROVEDMAINTENANCES";
export const FETCH_APPROVEDMAINTENANCE = "FETCH_APPROVEDMAINTENANCE";
export const DELETE_APPROVEDMAINTENANCE = "DELETE_APPROVEDMAINTENANCE";
export const EDIT_APPROVEDMAINTENANCE = "EDIT_APPROVEDMAINTENANCE";

// for executed maintenance action types
export const CREATE_EXECUTEDMAINTENANCE = "CREATE_EXECUTEDMAINTENANCE";
export const FETCH_EXECUTEDMAINTENANCES = "FETCH_EXECUTEDMAINTENANCES";
export const FETCH_EXECUTEDMAINTENANCE = "FETCH_EXECUTEDMAINTENANCE";
export const DELETE_EXECUTEDMAINTENANCE = "DELETE_EXECUTEDMAINTENANCE";
export const EDIT_EXECUTEDMAINTENANCE = "EDIT_EXECUTEDMAINTENANCE";

// for asset inventory action types
export const MAKE_INVENTORYREQUISITIONREQUEST =
  "MAKE_INVENTORYREQUISITIONREQUEST";
export const MAKE_INVENTORYDISPOSALREQUEST = "MAKE_INVENTORYDISPOSALREQUEST";
export const MAKE_INVENTORYRETIREMENTREQUEST =
  "MAKE_INVENTORYRETIREMENTREQUEST";
export const MAKE_INVENTORYTRANSFERREQUEST = "MAKE_INVENTORYTRANSFERREQUEST";
export const FETCH_INVENTORYSTOCKS = "FETCH_INVENTORYSTOCKS";
export const FETCH_INVENTORYSTOCK = "FETCH_INVENTORYSTOCK";
export const DELETE_INVENTORYSTOCK = "DELETE_INVENTORYSTOCK";
export const EDIT_INVENTORYSTOCK = "EDIT_INVENTORYSTOCK";

// for unapproved requisition action types
export const FETCH_UNAPPROVEDSTOCKREQUISITIONS =
  "FETCH_UNAPPROVEDSTOCKREQUISITIONS";
export const FETCH_UNAPPROVEDSTOCKREQUISITION =
  "FETCH_UNAPPROVEDSTOCKREQUISITION";
export const DELETE_UNAPPROVEDSTOCKREQUISITION =
  "DELETE_UNAPPROVEDSTOCKREQUISITION";
export const EDIT_UNAPPROVEDSTOCKREQUISITION =
  "EDIT_UNAPPROVEDSTOCKREQUISITION";

// for unapproved retirement action types
export const FETCH_UNAPPROVEDSTOCKRETIREMENTS =
  "FETCH_UNAPPROVEDSTOCKRETIREMENTS";
export const FETCH_UNAPPROVEDSTOCKRETIREMENT =
  "FETCH_UNAPPROVEDSTOCKRETIREMENT";
export const DELETE_UNAPPROVEDSTOCKRETIREMENT =
  "DELETE_UNAPPROVEDSTOCKRETIREMENT";
export const EDIT_UNAPPROVEDSTOCKRETIREMENT = "EDIT_UNAPPROVEDSTOCKRETIREMENT";

// for unapproved disposal action types
export const FETCH_UNAPPROVEDSTOCKDISPOSITIONS =
  "FETCH_UNAPPROVEDSTOCKDISPOSITIONS";
export const FETCH_UNAPPROVEDSTOCKDISPOSITION =
  "FETCH_UNAPPROVEDSTOCKDISPOSITION";
export const DELETE_UNAPPROVEDSTOCKDISPOSITION =
  "DELETE_UNAPPROVEDSTOCKDISPOSITION";
export const EDIT_UNAPPROVEDSTOCKDISPOSITION =
  "EDIT_UNAPPROVEDSTOCKDISPOSITION";

// for unapproved transfers & lease action types
export const FETCH_UNAPPROVEDSTOCKTRANSFERS = "FETCH_UNAPPROVEDSTOCKTRANSFERS";
export const FETCH_UNAPPROVEDSTOCKTRANSFER = "FETCH_UNAPPROVEDSTOCKTRANSFER";
export const DELETE_UNAPPROVEDSTOCKTRANSFER = "DELETE_UNAPPROVEDSTOCKTRANSFER";
export const EDIT_UNAPPROVEDSTOCKTRANSFER = "EDIT_UNAPPROVEDSTOCKTRANSFER";

// for asset requisition action types
export const FETCH_ASSETREQUISITIONS = "FETCH_ASSETREQUISITIONS";
export const FETCH_ASSETREQUISITION = "FETCH_ASSETREQUISITION";
export const DELETE_ASSETREQUISITION = "DELETE_ASSETREQUISITION";
export const EDIT_ASSETREQUISITION = "EDIT_ASSETREQUISITION";

// for asset pending quisition action types
export const FETCH_PENDINGASSETREQUISITIONS = "FETCH_PENDINGASSETREQUISITIONS";
export const FETCH_PENDINGASSETREQUISITION = "FETCH_PENDINGASSETREQUISITION";
export const DELETE_PENDINGASSETREQUISITION = "DELETE_PENDINGASSETREQUISITION";
export const EDIT_PENDINGASSETREQUISITION = "EDIT_PENDINGASSETREQUISITION";

// for asset withdrawn requisition action types
export const FETCH_WITHDRAWNASSETREQUISITIONS =
  "FETCH_WITHDRAWNASSETREQUISITIONS";
export const FETCH_WITHDRAWNASSETREQUISITION =
  "FETCH_WITHDRAWNASSETREQUISITION";
export const DELETE_WITHDRAWNASSETREQUISITION =
  "DELETE_WITHDRAWNASSETREQUISITION";
export const EDIT_WITHDRAWNASSETREQUISITION = "EDIT_WITHDRAWNASSETREQUISITION";

// for asset aborted requisition action types
export const FETCH_ABORTEDASSETREQUISITIONS = "FETCH_ABORTEDASSETREQUISITIONS";
export const FETCH_ABORTEDASSETREQUISITION = "FETCH_ABORTEDASSETREQUISITION";
export const DELETE_ABORTEDASSETREQUISITION = "DELETE_ABORTEDASSETREQUISITION";
export const EDIT_ABORTEDASSETREQUISITION = "EDIT_ABORTEDASSETREQUISITION";

// for asset returns post requisition action types
export const FETCH_RETURNASSETPOSTREQUISITIONS =
  "FETCH_RETURNASSETPOSTREQUISITIONS";
export const FETCH_RETURNASSETPOSTREQUISITION =
  "FETCH_RETURNASSETPOSTREQUISITION";
export const DELETE_RETURNASSETPOSTREQUISITION =
  "DELETE_RETURNASSETPOSTREQUISITION";
export const EDIT_RETURNASSETPOSTREQUISITION =
  "EDIT_RETURNASSETPOSTREQUISITION";
