//for authenticatiob and authorization
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP = "SIGN_UP";

//for category resources
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";

// for user resources
export const CREATE_USER = "CREATE_USER";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER = "FETCH_USER";
export const DELETE_USER = "DELETE_USER";
export const EDIT_USER = "EDIT_USER";

// for city resources
export const CREATE_CITY = "CREATE_CITY";
export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CITY = "FETCH_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const EDIT_CITY = "EDIT_CITY";

// for vendor resources
export const CREATE_VENDOR = "CREATE_VENDOR";
export const FETCH_VENDORS = "FETCH_VENDORS";
export const FETCH_VENDOR = "FETCH_VENDOR";
export const DELETE_VENDOR = "DELETE_VENDOR";
export const EDIT_VENDOR = "EDIT_VENDOR";

// for product resources
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";

// for policy resources
export const CREATE_POLICY = "CREATE_POLICY";
export const FETCH_POLICIES = "FETCH_POLICIES";
export const FETCH_POLICY = "FETCH_POLICY";
export const DELETE_POLICY = "DELETE_POLICY";
export const EDIT_POLICY = "EDIT_POLICY";

// for countries resources
export const CREATE_COUNTRY = "CREATE_COUNTRY";
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const EDIT_COUNTRY = "EDIT_COUNTRY";

// for state resources
export const CREATE_STATE = "CREATE_STATE";
export const FETCH_STATES = "FETCH_STATES";
export const FETCH_STATE = "FETCH_STATE";
export const DELETE_STATE = "DELETE_STATE";
export const EDIT_STATE = "EDIT_STATE";

// for currency resources
export const CREATE_CURRENCY = "CREATE_CURRENCY";
export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const FETCH_CURRENCY = "FETCH_CURRENCY";
export const DELETE_CURRENCY = "DELETE_CURRENCY";
export const EDIT_CURRENCY = "EDIT_CURRENCY";

// for Scheme Codes
export const CREATE_SCHEMECODE = "CREATE_SCHEMECODE";
export const FETCH_SCHEMECODES = "FETCH_SCHEMECODES";
export const FETCH_SCHEMECODE = "FETCH_SCHEMECODE";
export const DELETE_SCHEMECODE = "DELETE_SCHEMECODE";
export const EDIT_SCHEMECODE = "EDIT_SCHEMECODE";

// for General Ledger Codes
export const CREATE_GLCODE = "CREATE_GLCODE";
export const FETCH_GLCODES = "FETCH_GLCODES";
export const FETCH_GLCODE = "FETCH_GLCODE";
export const DELETE_GLCODE = "DELETE_GLCODE";
export const EDIT_GLCODE = "EDIT_GLCODE";

// for General Subsidiar Ledger Codes
export const CREATE_SUBGLCODE = "CREATE_SUBGLCODE";
export const FETCH_SUBGLCODES = "FETCH_SUBGLCODES";
export const FETCH_SUBGLCODE = "FETCH_SUBGLCODE";
export const DELETE_SUBGLCODE = "DELETE_SUBGLCODE";
export const EDIT_GLSUBCODE = "EDIT_GLSUBCODE";

// for Transaction types
export const CREATE_TRANSTYPE = "CREATE_TRANSTYPE";
export const FETCH_TRANSTYPES = "FETCH_TRANSTYPES";
export const FETCH_TRANSTYPE = "FETCH_TRANSTYPE";
export const DELETE_TRANSTYPE = "DELETE_TRANSTYPE";
export const EDIT_TRANSTYPE = "EDIT_TRANSTYPE";

// for Service Outlets
export const CREATE_SERVICEOUTLET = "CREATE_SERVICEOUTLET";
export const FETCH_SERVICEOUTLETS = "FETCH_SERVICEOUTLETS";
export const FETCH_SERVICEOUTLET = "FETCH_SERVICEOUTLET";
export const DELETE_SERVICEOUTLET = "DELETE_SERVICEOUTLET";
export const EDIT_SERVICEOUTLET = "EDIT_SERVICEOUTLET";

// for Locations
export const CREATE_LOCATION = "CREATE_LOCATION";
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const FETCH_LOCATION = "FETCH_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const EDIT_LOCATION_SUCCEEDED = "EDIT_LOCATION_SUCCEEDED";
export const EDIT_LOCATION_FAILED = "EDIT_LOCATION_FAILED";

// for Headoffice Service Outlets
export const CREATE_HOSERVICEOUTLET = "CREATE_HOSERVICEOUTLET";
export const FETCH_HOSERVICEOUTLETS = "FETCH_HOSERVICEOUTLETS";
export const FETCH_HOSERVICEOUTLET = "FETCH_HOSERVICEOUTLET";
export const DELETE_HOSERVICEOUTLET = "DELETE_HOSERVICEOUTLET";
export const EDIT_HOSERVICEOUTLET = "EDIT_HOSERVICEOUTLET";

// for Office Operations and Services
export const CREATE_OFFICEOPERATION = "CREATE_OFFICEOPERATION";
export const FETCH_OFFICEOPERATIONS = "FETCH_OFFICEOPERATIONS";
export const FETCH_OFFICEOPERATION = "FETCH_OFFICEOPERATION";
export const DELETE_OFFICEOPERATION = "DELETE_OFFICEOPERATION";
export const EDIT_OFFICEOPERATION = "EDIT_OFFICEOPERATION";

// for asset store types
export const CREATE_STORETYPE = "CREATE_STORETYPE";
export const FETCH_STORETYPES = "FETCH_STORETYPES";
export const FETCH_STORETYPE = "FETCH_STORETYPE";
export const DELETE_STORETYPE = "DELETE_STORETYPE";
export const EDIT_STORETYPE = "EDIT_STORETYPE";

// for asset subclasses
export const CREATE_SUBCLASS = "CREATE_SUBCLASS";
export const FETCH_SUBCLASSES = "FETCH_SUBCLASSES";
export const FETCH_SUBCLASS = "FETCH_SUBCLASS";
export const DELETE_SUBCLASS = "DELETE_SUBCLASS";
export const EDIT_SUBCLASS = "EDIT_SUBCLASS";

// for asset asset types
export const CREATE_ASSETTYPE = "CREATE_ASSETTYPE";
export const FETCH_ASSETTYPES = "FETCH_ASSETTYPES";
export const FETCH_ASSETTYPE = "FETCH_ASSETTYPE";
export const DELETE_ASSETTYPE = "DELETE_ASSETTYPE";
export const EDIT_ASSETTYPE = "EDIT_ASSETTYPE";

// for asset depreciation types
export const CREATE_DEPRECIATIONTYPE = "CREATE_DEPRECIATIONTYPE";
export const FETCH_DEPRECIATIONTYPES = "FETCH_DEPRECIATIONTYPES";
export const FETCH_DEPRECIATIONTYPE = "FETCH_DEPRECIATIONTYPE";
export const DELETE_DEPRECIATIONTYPE = "DELETE_DEPRECIATIONTYPE";
export const EDIT_DEPRECIATIONTYPE = "EDIT_DEPRECIATIONTYPE";

// for asset maintenance types
export const CREATE_MAINTENANCETYPE = "CREATE_MAINTENANCETYPE";
export const FETCH_MAINTENANCETYPES = "FETCH_MAINTENANCETYPES";
export const FETCH_MAINTENANCETYPE = "FETCH_MAINTENANCETYPE";
export const DELETE_MAINTENANCETYPE = "DELETE_MAINTENANCETYPE";
export const EDIT_MAINTENANCETYPE = "EDIT_MAINTENANCETYPE";

// for asset measurement units
export const CREATE_MEASUREMENTUNIT = "CREATE_MEASUREMENTUNIT";
export const FETCH_MEASUREMENTUNITS = "FETCH_MEASUREMENTUNITS";
export const FETCH_MEASUREMENTUNIT = "FETCH_MEASUREMENTUNIT";
export const DELETE_MEASUREMENTUNIT = "DELETE_MEASUREMENTUNIT";
export const EDIT_MEASUREMENTUNIT = "EDIT_MEASUREMENTUNIT";

// for asset and stocks
export const CREATE_STOCK = "CREATE_STOCK";
export const FETCH_STOCKS = "FETCH_STOCKS";
export const FETCH_STOCK = "FETCH_STOCK";
export const DELETE_STOCK = "DELETE_STOCK";
export const EDIT_STOCK = "EDIT_STOCK";

// for other assets
export const CREATE_OTHERASSET = "CREATE_OTHERASSET";
export const FETCH_OTHERASSETS = "FETCH_OTHERASSETS";
export const FETCH_OTHERASSET = "FETCH_OTHERASSET";
export const DELETE_OTHERASSET = "DELETE_OTHERASSET";
export const EDIT_OTHERASSET = "EDIT_OTHERASSET";

// for unapproved procurement actions
export const CREATE_UNAPPROVEDPROCUREMENT = "CREATE_UNAPPROVEDPROCUREMENT";
export const FETCH_UNAPPROVEDPROCUREMENTS = "FETCH_UNAPPROVEDPROCUREMENTS";
export const FETCH_UNAPPROVEDPROCUREMENT = "FETCH_UNAPPROVEDPROCUREMENT";
export const DELETE_UNAPPROVEDPROCUREMENT = "DELETE_UNAPPROVEDPROCUREMENT";
export const EDIT_UNAPPROVEDPROCUREMENT = "EDIT_UNAPPROVEDPROCUREMENT";

// for approved procurement actions
export const CREATE_APPROVEDPROCUREMENT = "CREATE_APPROVEDPROCUREMENT";
export const FETCH_APPROVEDPROCUREMENTS = "FETCH_APPROVEDPROCUREMENTS";
export const FETCH_APPROVEDPROCUREMENT = "FETCH_APPROVEDPROCUREMENT";
export const DELETE_APPROVEDPROCUREMENT = "DELETE_APPROVEDPROCUREMENT";
export const EDIT_APPROVEDPROCUREMENT = "EDIT_APPROVEDPROCUREMENT";

// for executed procurement actions
export const CREATE_EXECAPPROVEDPROCUREMENT = "CREATE_EXECAPPROVEDPROCUREMENT";
export const FETCH_EXECAPPROVEDPROCUREMENTS = "FETCH_EXECAPPROVEDPROCUREMENTS";
export const FETCH_EXECAPPROVEDPROCUREMENT = "FETCH_EXECAPPROVEDPROCUREMENT";
export const DELETE_EXECAPPROVEDPROCUREMENT = "DELETE_EXECAPPROVEDPROCUREMENT";
export const EDIT_EXECAPPROVEDPROCUREMENT = "EDIT_EXECAPPROVEDPROCUREMENT";

// for unapproved maintenance action types
export const CREATE_UNAPPROVEDMAINTENANCE = "CREATE_UNAPPROVEDMAINTENANCE";
export const FETCH_UNAPPROVEDMAINTENANCES = "FETCH_UNAPPROVEDMAINTENANCES";
export const FETCH_UNAPPROVEDMAINTENANCE = "FETCH_UNAPPROVEDMAINTENANCE";
export const DELETE_UNAPPROVEDMAINTENANCE = "DELETE_UNAPPROVEDMAINTENANCE";
export const EDIT_UNAPPROVEDMAINTENANCE = "EDIT_UNAPPROVEDMAINTENANCE";

// for approved maintenance action types
export const CREATE_APPROVEDMAINTENANCE = "CREATE_APPROVEDMAINTENANCE";
export const FETCH_APPROVEDMAINTENANCES = "FETCH_APPROVEDMAINTENANCES";
export const FETCH_APPROVEDMAINTENANCE = "FETCH_APPROVEDMAINTENANCE";
export const DELETE_APPROVEDMAINTENANCE = "DELETE_APPROVEDMAINTENANCE";
export const EDIT_APPROVEDMAINTENANCE = "EDIT_APPROVEDMAINTENANCE";

// for executed maintenance action types
export const CREATE_EXECUTEDMAINTENANCE = "CREATE_EXECUTEDMAINTENANCE";
export const FETCH_EXECUTEDMAINTENANCES = "FETCH_EXECUTEDMAINTENANCES";
export const FETCH_EXECUTEDMAINTENANCE = "FETCH_EXECUTEDMAINTENANCE";
export const DELETE_EXECUTEDMAINTENANCE = "DELETE_EXECUTEDMAINTENANCE";
export const EDIT_EXECUTEDMAINTENANCE = "EDIT_EXECUTEDMAINTENANCE";

// for asset inventory action types
export const MAKE_INVENTORYREQUISITIONREQUEST =
  "MAKE_INVENTORYREQUISITIONREQUEST";
export const MAKE_INVENTORYDISPOSALREQUEST = "MAKE_INVENTORYDISPOSALREQUEST";
export const MAKE_INVENTORYRETIREMENTREQUEST =
  "MAKE_INVENTORYRETIREMENTREQUEST";
export const MAKE_INVENTORYTRANSFERREQUEST = "MAKE_INVENTORYTRANSFERREQUEST";
export const FETCH_INVENTORYSTOCKS = "FETCH_INVENTORYSTOCKS";
export const FETCH_INVENTORYSTOCK = "FETCH_INVENTORYSTOCK";
export const DELETE_INVENTORYSTOCK = "DELETE_INVENTORYSTOCK";
export const EDIT_INVENTORYSTOCK = "EDIT_INVENTORYSTOCK";

// for unapproved requisition action types
export const FETCH_UNAPPROVEDSTOCKREQUISITIONS =
  "FETCH_UNAPPROVEDSTOCKREQUISITIONS";
export const FETCH_UNAPPROVEDSTOCKREQUISITION =
  "FETCH_UNAPPROVEDSTOCKREQUISITION";
export const DELETE_UNAPPROVEDSTOCKREQUISITION =
  "DELETE_UNAPPROVEDSTOCKREQUISITION";
export const EDIT_UNAPPROVEDSTOCKREQUISITION =
  "EDIT_UNAPPROVEDSTOCKREQUISITION";

// for unapproved retirement action types
export const FETCH_UNAPPROVEDSTOCKRETIREMENTS =
  "FETCH_UNAPPROVEDSTOCKRETIREMENTS";
export const FETCH_UNAPPROVEDSTOCKRETIREMENT =
  "FETCH_UNAPPROVEDSTOCKRETIREMENT";
export const DELETE_UNAPPROVEDSTOCKRETIREMENT =
  "DELETE_UNAPPROVEDSTOCKRETIREMENT";
export const EDIT_UNAPPROVEDSTOCKRETIREMENT = "EDIT_UNAPPROVEDSTOCKRETIREMENT";

// for unapproved disposal action types
export const FETCH_UNAPPROVEDSTOCKDISPOSITIONS =
  "FETCH_UNAPPROVEDSTOCKDISPOSITIONS";
export const FETCH_UNAPPROVEDSTOCKDISPOSITION =
  "FETCH_UNAPPROVEDSTOCKDISPOSITION";
export const DELETE_UNAPPROVEDSTOCKDISPOSITION =
  "DELETE_UNAPPROVEDSTOCKDISPOSITION";
export const EDIT_UNAPPROVEDSTOCKDISPOSITION =
  "EDIT_UNAPPROVEDSTOCKDISPOSITION";

// for unapproved transfers & lease action types
export const FETCH_UNAPPROVEDSTOCKTRANSFERS = "FETCH_UNAPPROVEDSTOCKTRANSFERS";
export const FETCH_UNAPPROVEDSTOCKTRANSFER = "FETCH_UNAPPROVEDSTOCKTRANSFER";
export const DELETE_UNAPPROVEDSTOCKTRANSFER = "DELETE_UNAPPROVEDSTOCKTRANSFER";
export const EDIT_UNAPPROVEDSTOCKTRANSFER = "EDIT_UNAPPROVEDSTOCKTRANSFER";

// for asset requisition action types
export const FETCH_ASSETREQUISITIONS = "FETCH_ASSETREQUISITIONS";
export const FETCH_ASSETREQUISITION = "FETCH_ASSETREQUISITION";
export const DELETE_ASSETREQUISITION = "DELETE_ASSETREQUISITION";
export const EDIT_ASSETREQUISITION = "EDIT_ASSETREQUISITION";

// for asset pending quisition action types
export const FETCH_PENDINGASSETREQUISITIONS = "FETCH_PENDINGASSETREQUISITIONS";
export const FETCH_PENDINGASSETREQUISITION = "FETCH_PENDINGASSETREQUISITION";
export const DELETE_PENDINGASSETREQUISITION = "DELETE_PENDINGASSETREQUISITION";
export const EDIT_PENDINGASSETREQUISITION = "EDIT_PENDINGASSETREQUISITION";

// for asset withdrawn requisition action types
export const FETCH_WITHDRAWNASSETREQUISITIONS =
  "FETCH_WITHDRAWNASSETREQUISITIONS";
export const FETCH_WITHDRAWNASSETREQUISITION =
  "FETCH_WITHDRAWNASSETREQUISITION";
export const DELETE_WITHDRAWNASSETREQUISITION =
  "DELETE_WITHDRAWNASSETREQUISITION";
export const EDIT_WITHDRAWNASSETREQUISITION = "EDIT_WITHDRAWNASSETREQUISITION";

// for asset aborted requisition action types
export const FETCH_ABORTEDASSETREQUISITIONS = "FETCH_ABORTEDASSETREQUISITIONS";
export const FETCH_ABORTEDASSETREQUISITION = "FETCH_ABORTEDASSETREQUISITION";
export const DELETE_ABORTEDASSETREQUISITION = "DELETE_ABORTEDASSETREQUISITION";
export const EDIT_ABORTEDASSETREQUISITION = "EDIT_ABORTEDASSETREQUISITION";

// for asset returns post requisition action types
export const FETCH_RETURNASSETPOSTREQUISITIONS =
  "FETCH_RETURNASSETPOSTREQUISITIONS";
export const FETCH_RETURNASSETPOSTREQUISITION =
  "FETCH_RETURNASSETPOSTREQUISITION";
export const DELETE_RETURNASSETPOSTREQUISITION =
  "DELETE_RETURNASSETPOSTREQUISITION";
export const EDIT_RETURNASSETPOSTREQUISITION =
  "EDIT_RETURNASSETPOSTREQUISITION";

// for asset retirement action types
export const FETCH_ASSETRETIREMENTS = "FETCH_ASSETRETIREMENTS";
export const FETCH_ASSETRETIREMENT = "FETCH_ASSETRETIREMENT";
export const DELETE_ASSETRETIREMENT = "DELETE_ASSETRETIREMENT";
export const EDIT_ASSETRETIREMENT = "EDIT_ASSETRETIREMENT";

// for asset pending retirement action types
export const FETCH_PENDINGASSETRETIREMENTS = "FETCH_PENDINGASSETRETIREMENTS";
export const FETCH_PENDINGASSETRETIREMENT = "FETCH_PENDINGASSETRETIREMENT";
export const DELETE_PENDINGASSETRETIREMENT = "DELETE_PENDINGASSETRETIREMENT";
export const EDIT_PENDINGASSETRETIREMENT = "EDIT_PENDINGASSETRETIREMENT";

// for asset withdrawn retirement action types
export const FETCH_WITHDRAWNASSETRETIREMENTS =
  "FETCH_WITHDRAWNASSETRETIREMENTS";
export const FETCH_WITHDRAWNASSETRETIREMENT = "FETCH_WITHDRAWNASSETRETIREMENT";
export const DELETE_WITHDRAWNASSETRETIREMENT =
  "DELETE_WITHDRAWNASSETRETIREMENT";
export const EDIT_WITHDRAWNASSETRETIREMENT = "EDIT_WITHDRAWNASSETRETIREMENT";

// for asset return post  retirement action types
export const FETCH_RETURNPOSTASSETRETIREMENTS =
  "FETCH_RETURNPOSTASSETRETIREMENTS";
export const FETCH_RETURNPOSTASSETRETIREMENT =
  "FETCH_RETURNPOSTASSETRETIREMENT";
export const DELETE_RETURNPOSTASSETRETIREMENT =
  "DELETE_RETURNPOSTASSETRETIREMENT";
export const EDIT_RETURNPOSTASSETRETIREMENT = "EDIT_RETURNPOSTASSETRETIREMENT";

// for asset dispositions action types
export const FETCH_ASSETDISPOSITIONS = "FETCH_ASSETDISPOSITIONS";
export const FETCH_ASSETDISPOSITION = "FETCH_ASSETDISPOSITION";
export const DELETE_ASSETDISPOSITION = "DELETE_ASSETDISPOSITION";
export const EDIT_ASSETDISPOSITION = "EDIT_ASSETDISPOSITION";

// for asset pending dispositions action types
export const FETCH_PENDINGASSETDISPOSITIONS = "FETCH_PENDINGASSETDISPOSITIONS";
export const FETCH_PENDINGASSETDISPOSITION = "FETCH_PENDINGASSETDISPOSITION";
export const DELETE_PENDINGASSETDISPOSITION = "DELETE_PENDINGASSETDISPOSITION";
export const EDIT_PENDINGASSETDISPOSITION = "EDIT_PENDINGASSETDISPOSITION";

// for asset withdrawn dispositions action types
export const FETCH_WITHDRAWNASSETDISPOSITIONS =
  "FETCH_WITHDRAWNASSETDISPOSITIONS";
export const FETCH_WITHDRAWNASSETDISPOSITION =
  "FETCH_WITHDRAWNASSETDISPOSITION";
export const DELETE_WITHDRAWNASSETDISPOSITION =
  "DELETE_WITHDRAWNASSETDISPOSITION";
export const EDIT_WITHDRAWNASSETDISPOSITION = "EDIT_WITHDRAWNASSETDISPOSITION";

// for return asset post dispositions action types
export const FETCH_RETURNASSETPOSTDISPOSITIONS =
  "FETCH_RETURNASSETPOSTDISPOSITIONS";
export const FETCH_RETURNASSETPOSTDISPOSITION =
  "FETCH_RETURNASSETPOSTDISPOSITION";
export const DELETE_RETURNASSETPOSTDISPOSITION =
  "DELETE_RETURNASSETPOSTDISPOSITION";
export const EDIT_RETURNASSETPOSTDISPOSITION =
  "EDIT_RETURNASSETPOSTDISPOSITION";

// for asset movements action types
export const CREATE_ASSETMOVEMENT = "CREATE_ASSETMOVEMENT";
export const FETCH_ASSETMOVEMENTS = "FETCH_ASSETMOVEMENTS";
export const FETCH_ASSETMOVEMENT = "FETCH_ASSETMOVEMENT";
export const DELETE_ASSETMOVEMENT = "DELETE_ASSETMOVEMENT";
export const EDIT_ASSETMOVEMENT = "EDIT_ASSETMOVEMENT";

// for asset transfer movements action types
export const CREATE_TRANSFERASSETMOVEMENT = "CREATE_TRANSFERASSETMOVEMENT";
export const FETCH_TRANSFERASSETMOVEMENTS = "FETCH_TRANSFERASSETMOVEMENTS";
export const FETCH_TRANSFERASSETMOVEMENT = "FETCH_TRANSFERASSETMOVEMENT";
export const DELETE_TRANSFERASSETMOVEMENT = "DELETE_TRANSFERASSETMOVEMENT";
export const EDIT_TRANSFERASSETMOVEMENT = "EDIT_TRANSFERASSETMOVEMENT";

// for asset pending transfer movements action types
export const CREATE_PENDINGTRANSFERASSETMOVEMENT =
  "CREATE_PENDINGTRANSFERASSETMOVEMENT";
export const FETCH_PENDINGTRANSFERASSETMOVEMENTS =
  "FETCH_PENDINGTRANSFERASSETMOVEMENTS";
export const FETCH_PENDINGTRANSFERASSETMOVEMENT =
  "FETCH_PENDINGTRANSFERASSETMOVEMENT";
export const DELETE_PENDINGTRANSFERASSETMOVEMENT =
  "DELETE_PENDINGTRANSFERASSETMOVEMENT";
export const EDIT_PENDINGTRANSFERASSETMOVEMENT =
  "EDIT_PENDINGTRANSFERASSETMOVEMENT";

// for asset WITHDRAWN transfer movements action types
export const CREATE_WITHDRAWNTRANSFERASSETMOVEMENT =
  "CREATE_WITHDRAWNTRANSFERASSETMOVEMENT";
export const FETCH_WITHDRAWNTRANSFERASSETMOVEMENTS =
  "FETCH_WITHDRAWNTRANSFERASSETMOVEMENTS";
export const FETCH_WITHDRAWNTRANSFERASSETMOVEMENT =
  "FETCH_WITHDRAWNTRANSFERASSETMOVEMENT";
export const DELETE_WITHDRAWNTRANSFERASSETMOVEMENT =
  "DELETE_WITHDRAWNTRANSFERASSETMOVEMENT";
export const EDIT_WITHDRAWNTRANSFERASSETMOVEMENT =
  "EDIT_WITHDRAWNTRANSFERASSETMOVEMENT";

// for asset returned transfer movements action types
export const CREATE_RETURNASSETPOSTTRANSFERMOVEMENT =
  "CREATE_RETURNASSETPOSTTRANSFERMOVEMENT";
export const FETCH_RETURNASSETPOSTTRANSFERMOVEMENTS =
  "FETCH_RETURNASSETPOSTTRANSFERMOVEMENTS";
export const FETCH_RETURNASSETPOSTTRANSFERMOVEMENT =
  "FETCH_RETURNASSETPOSTTRANSFERMOVEMENT";
export const DELETE_RETURNASSETPOSTTRANSFERMOVEMENT =
  "DELETE_RETURNASSETPOSTTRANSFERMOVEMENT";
export const EDIT_RETURNASSETPOSTTRANSERMOVEMENT =
  "EDIT_RETURNASSETPOSTTRANSERMOVEMENT";

// for asset store action types
export const CREATE_ASSETSTORE = "CREATE_ASSETSTORE";
export const FETCH_ASSETSTORES = "FETCH_ASSETSTORES";
export const FETCH_ASSETSTORE = "FETCH_ASSETSTORE";
export const DELETE_ASSETSTORE = "DELETE_ASSETSTORE";
export const EDIT_ASSETSTORE = "EDIT_ASSETSTORE";

// for asset store maintenance  action types
export const CREATE_MAINTENANCEASSETSTORE = "CREATE_MAINTENANCEASSETSTORE";
export const FETCH_MAINTENANCEASSETSTORES = "FETCH_MAINTENANCEASSETSTORES";
export const FETCH_MAINTENANCEASSETSTORE = "FETCH_MAINTENANCEASSETSTORE";
export const DELETE_MAINTENANCEASSETSTORE = "DELETE_MAINTENANCEASSETSTORE";
export const EDIT_MAINTENANCEASSETSTORE = "EDIT_MAINTENANCEASSETSTORE";

// for asset store lease  action types
export const CREATE_LEASEASSETSTORE = "CREATE_LEASEASSETSTORE";
export const FETCH_LEASEASSETSTORES = "FETCH_LEASEASSETSTORES";
export const FETCH_LEASEASSETSTORE = "FETCH_LEASEASSETSTORE";
export const DELETE_LEASEASSETSTORE = "DELETE_LEASEASSETSTORE";
export const EDIT_LEASEASSETSTORE = "EDIT_LEASEASSETSTORE";

// for asset store ownership  action types
export const CREATE_OWNERSHIPASSETSTORE = "CREATE_OWNERSHIPASSETSTORE";
export const FETCH_OWNERSHIPASSETSTORES = "FETCH_OWNERSHIPASSETSTORES";
export const FETCH_OWNERSHIPASSETSTORE = "FETCH_OWNERSHIPASSETSTORE";
export const DELETE_OWNERSHIPASSETSTORE = "DELETE_OWNERSHIPASSETSTORE";
export const EDIT_OWNERSHIPASSETSTORE = "EDIT_OWNERSHIPASSETSTORE";

// for asset store space allocation  action types
export const CREATE_ASSETSTORESPACEALLOCATION =
  "CREATE_ASSETSTORESPACEALLOCATION";
export const FETCH_ASSETSTORESPACEALLOCATIONS =
  "FETCH_ASSETSTORESPACEALLOCATIONS";
export const FETCH_ASSETSTORESPACEALLOCATION =
  "FETCH_ASSETSTORESPACEALLOCATION";
export const DELETE_ASSETSTORESPACEALLOCATION =
  "DELETE_ASSETSTORESPACEALLOCATION";
export const EDIT_ASSETSTORESPACEALLOCATION = "EDIT_ASSETSTORESPACEALLOCATION";

// for asset store sell  action types
export const CREATE_SELLASSETSTORE = "CREATE_SELLASSETSTORE";
export const FETCH_SELLASSETSTORES = "FETCH_SELLASSETSTORES";
export const FETCH_SELLASSETSTORE = "FETCH_SELLASSETSTORE";
export const DELETE_SELLASSETSTORE = "DELETE_SELLASSETSTORE";
export const EDIT_SELLASSETSTORE = "EDIT_SELLASSETSTORE";

// for asset store closure  action types
export const CREATE_ASSETSTORECLOSURE = "CREATE_ASSETSTORECLOSURE";
export const FETCH_ASSETSTORECLOSURES = "FETCH_ASSETSTORECLOSURES";
export const FETCH_ASSETSTORECLOSURE = "FETCH_ASSETSTORECLOSURE";
export const DELETE_ASSETSTORECLOSURE = "DELETE_ASSETSTORECLOSURE";
export const EDIT_ASSETSTORECLOSURE = "EDIT_ASSETSTORECLOSURE";

// for asset utility movement type  action types
export const CREATE_STOREMOVEMENTTYPE = "CREATE_STOREMOVEMENTTYPE";
export const FETCH_STOREMOVEMENTTYPES = "FETCH_STOREMOVEMENTTYPES";
export const FETCH_STOREMOVEMENTTYPE = "FETCH_STOREMOVEMENTTYPE";
export const DELETE_STOREMOVEMENTTYPE = "DELETE_STOREMOVEMENTTYPE";
export const EDIT_STOREMOVEMENTTYPE = "EDIT_STOREMOVEMENTTYPE";

// for asset store disposition type  action types
export const CREATE_STOREDISPOSITIONTYPE = "CREATE_STOREDISPOSITIONTYPE";
export const FETCH_STOREDISPOSITIONTYPES = "FETCH_STOREDISPOSITIONTYPES";
export const FETCH_STOREDISPOSITIONTYPE = "FETCH_STOREDISPOSITIONTYPE";
export const DELETE_STOREDISPOSITIONTYPE = "DELETE_STOREDISPOSITIONTYPE";
export const EDIT_STOREDISPOSITIONTYPE = "EDIT_STOREDISPOSITIONTYPE";

// for asset maintenance type  action types
export const CREATE_STOREMAINTENANCETYPE = "CREATE_STOREMAINTENANCETYPE";
export const FETCH_STOREMAINTENANCETYPES = "FETCH_STOREMAINTENANCETYPES";
export const FETCH_STOREMAINTENANCETYPE = "FETCH_STOREMAINTENANCETYPE";
export const DELETE_STOREMAINTENANCETYPE = "DELETE_STOREMAINTENANCETYPE";
export const EDIT_STOREMAINTENANCETYPE = "EDIT_STOREMAINTENANCETYPE";

// for operation transformation type  action types
export const CREATE_TRANSFORMATIONTYPE = "CREATE_TRANSFORMATIONTYPE";
export const FETCH_TRANSFORMATIONTYPES = "FETCH_TRANSFORMATIONTYPES";
export const FETCH_TRANSFORMATIONTYPE = "FETCH_TRANSFORMATIONTYPE";
export const DELETE_TRANSFORMATIONTYPE = "DELETE_TRANSFORMATIONTYPE";
export const EDIT_TRANSFORMATIONTYPE = "EDIT_TRANSFORMATIONTYPE";

// for operation transformation phase  action types
export const CREATE_TRANSFORMATIONPHASE = "CREATE_TRANSFORMATIONPHASE";
export const FETCH_TRANSFORMATIONPHASES = "FETCH_TRANSFORMATIONPHASES";
export const FETCH_TRANSFORMATIONPHASE = "FETCH_TRANSFORMATIONPHASE";
export const DELETE_TRANSFORMATIONPHASE = "DELETE_TRANSFORMATIONPHASE";
export const EDIT_TRANSFORMATIONPHASE = "EDIT_TRANSFORMATIONPHASE";

// for operation transformation phase event  action types
export const CREATE_TRANSFORMATIONPHASEEVENT =
  "CREATE_TRANSFORMATIONPHASEEVENT";
export const FETCH_TRANSFORMATIONPHASEEVENTS =
  "FETCH_TRANSFORMATIONPHASEEVENTS";
export const FETCH_TRANSFORMATIONPHASEEVENT = "FETCH_TRANSFORMATIONPHASEEVENT";
export const DELETE_TRANSFORMATIONPHASEEVENT =
  "DELETE_TRANSFORMATIONPHASEEVENT";
export const EDIT_TRANSFORMATIONPHASEEVENT = "EDIT_TRANSFORMATIONPHASEEVENT";

// for operation finishing types  action types
export const CREATE_FINISHINGTYPE = "CREATE_FINISHINGTYPE";
export const FETCH_FINISHINGTYPES = "FETCH_FINISHINGTYPES";
export const FETCH_FINISHINGTYPE = "FETCH_FINISHINGTYPE";
export const DELETE_FINISHINGTYPE = "DELETE_FINISHINGTYPE";
export const EDIT_FINISHINGTYPE = "EDIT_FINISHINGTYPE";

// for operation quality assurance types  action types
export const CREATE_QUALITYASSURANCETYPE = "CREATE_QUALITYASSURANCETYPE";
export const FETCH_QUALITYASSURANCETYPES = "FETCH_QUALITYASSURANCETYPES";
export const FETCH_QUALITYASSURANCETYPE = "FETCH_QUALITYASSURANCETYPE";
export const DELETE_QUALITYASSURANCETYPE = "DELETE_QUALITYASSURANCETYPE";
export const EDIT_QUALITYASSURANCETYPE = "EDIT_QUALITYASSURANCETYPE";

// for operation quality assurance phases  action types
export const CREATE_QUALITYASSURANCEPHASE = "CREATE_QUALITYASSURANCEPHASE";
export const FETCH_QUALITYASSURANCEPHASES = "FETCH_QUALITYASSURANCEPHASES";
export const FETCH_QUALITYASSURANCEPHASE = "FETCH_QUALITYASSURANCEPHASE";
export const DELETE_QUALITYASSURANCEPHASE = "DELETE_QUALITYASSURANCEPHASE";
export const EDIT_QUALITYASSURANCEPHASE = "EDIT_QUALITYASSURANCEPHASE";

// for operation quality assurance phase events  action types
export const CREATE_QUALITYASSURANCEPHASEEVENT =
  "CREATE_QUALITYASSURANCEPHASEEVENT";
export const FETCH_QUALITYASSURANCEPHASEEVENTS =
  "FETCH_QUALITYASSURANCEPHASEEVENTS";
export const FETCH_QUALITYASSURANCEPHASEEVENT =
  "FETCH_QUALITYASSURANCEPHASEEVENT";
export const DELETE_QUALITYASSURANCEPHASEEVENT =
  "DELETE_QUALITYASSURANCEPHASEEVENT";
export const EDIT_QUALITYASSURANCEPHASEEVENT =
  "EDIT_QUALITYASSURANCEPHASEEVENT";

// for operations maintenance types
export const CREATE_OPERATIONMAINTENANCETYPE =
  "CREATE_OPERATIONMAINTENANCETYPE";
export const FETCH_OPERATIONMAINTENANCETYPES =
  "FETCH_OPERATIONMAINTENANCETYPES";
export const FETCH_OPERATIONMAINTENANCETYPE = "FETCH_OPERATIONMAINTENANCETYPE";
export const DELETE_OPERATIONMAINTENANCETYPE =
  "DELETE_OPERATIONMAINTENANCETYPE";
export const EDIT_OPERATIONMAINTENANCETYPE = "EDIT_OPERATIONMAINTENANCETYPE";

// for operations on finishings
export const CREATE_FINISHING = "CREATE_FINISHING";
export const FETCH_FINISHINGS = "FETCH_FINISHINGS";
export const FETCH_FINISHING = "FETCH_FINISHING";
export const DELETE_FINISHING = "DELETE_FINISHING";
export const EDIT_FINISHING = "EDIT_FINISHING";

// for operations on quality assurance
export const CREATE_QUALITYASSURANCE = "CREATE_QUALITYASSURANCE";
export const FETCH_QUALITYASSURANCES = "FETCH_QUALITYASSURANCES";
export const FETCH_QUALITYASSURANCE = "FETCH_QUALITYASSURANCE";
export const DELETE_QUALITYASSURANCE = "DELETE_QUALITYASSURANCE";
export const EDIT_QUALITYASSURANCE = "EDIT_QUALITYASSURANCE";

// for operation maintenance
export const CREATE_OPERATIONMAINTENANCE = "CREATE_OPERATIONMAINTENANCE";
export const FETCH_OPERATIONMAINTENANCES = "FETCH_OPERATIONMAINTENANCES";
export const FETCH_OPERATIONMAINTENANCE = "FETCH_OPERATIONMAINTENANCE";
export const DELETE_OPERATIONMAINTENANCE = "DELETE_OPERATIONMAINTENANCE";
export const EDIT_OPERATIONMAINTENANCE = "EDIT_OPERATIONMAINTENANCE";

// for operation on processing
export const CREATE_OPERATIONPROCESSING = "CREATE_OPERATIONPROCESSING";
export const FETCH_OPERATIONPROCESSINGS = "FETCH_OPERATIONPROCESSINGS";
export const FETCH_OPERATIONPROCESSING = "FETCH_OPERATIONPROCESSING";
export const DELETE_OPERATIONPROCESSING = "DELETE_OPERATIONPROCESSING";
export const EDIT_OPERATIONPROCESSING = "EDIT_OPERATIONPROCESSING";

// for operation on processing
export const CREATE_OPERATIONOPERATION = "CREATE_OPERATIONOPERATION";
export const FETCH_OPERATIONOPERATIONS = "FETCH_OPERATIONOPERATIONS";
export const FETCH_OPERATIONOPERATION = "FETCH_OPERATIONOPERATION";
export const DELETE_OPERATIONOPERATION = "DELETE_OPERATIONOPERATION";
export const EDIT_OPERATIONOPERATION = "EDIT_OPERATIONOPERATION";

// for operation production maintenance
export const CREATE_OPERATIONPRODUCTIONMAINTENANCE =
  "CREATE_OPERATIONPRODUCTIONMAINTENANCE";
export const FETCH_OPERATIONPRODUCTIONMAINTENANCES =
  "FETCH_OPERATIONPRODUCTIONMAINTENANCES";
export const FETCH_OPERATIONPRODUCTIONMAINTENANCE =
  "FETCH_OPERATIONPRODUCTIONMAINTENANCE";
export const DELETE_OPERATIONPRODUCTIONMAINTENANCE =
  "DELETE_OPERATIONPRODUCTIONMAINTENANCE";
export const EDIT_OPERATIONPRODUCTIONMAINTENANCE =
  "EDIT_OPERATIONPRODUCTIONMAINTENANCE";

// for operations on production  quality assurance
export const CREATE_PRODUCTIONQUALITYASSURANCE =
  "CREATE_PRODUCTIONQUALITYASSURANCE";
export const FETCH_PRODUCTIONQUALITYASSURANCES =
  "FETCH_PRODUCTIONQUALITYASSURANCES";
export const FETCH_PRODUCTIONQUALITYASSURANCE =
  "FETCH_PRODUCTIONQUALITYASSURANCE";
export const DELETE_PRODUCTIONQUALITYASSURANCE =
  "DELETE_PRODUCTIONQUALITYASSURANCE";
export const EDIT_PRODUCTIONQUALITYASSURANCE =
  "EDIT_PRODUCTIONQUALITYASSURANCE";

// for operations on production finishings
export const CREATE_PRODUCTIONFINISHING = "CREATE_PRODUCTIONFINISHING";
export const FETCH_PRODUCTIONFINISHINGS = "FETCH_PRODUCTIONFINISHINGS";
export const FETCH_PRODUCTIONFINISHING = "FETCH_PRODUCTIONFINISHING";
export const DELETE_PRODUCTIONFINISHING = "DELETE_PRODUCTIONFINISHING";
export const EDIT_PRODUCTIONFINISHING = "EDIT_PRODUCTIONFINISHING";

// for projects on projects
export const CREATE_PROJECTPROJECT = "CREATE_PROJECTPROJECT";
export const FETCH_PROJECTPROJECTS = "FETCH_PROJECTPROJECTS";
export const FETCH_PROJECTPROJECT = "FETCH_PROJECTPROJECT";
export const DELETE_PROJECTPROJECT = "DELETE_PROJECTPROJECT";
export const EDIT_PROJECTPROJECT = "EDIT_PROJECTPROJECT";

// for projects on projects resources
export const CREATE_PROJECTPROJECTRESOURCE = "CREATE_PROJECTPROJECTRESOURCE";
export const FETCH_PROJECTPROJECTRESOURCES = "FETCH_PROJECTPROJECTRESOURCES";
export const FETCH_PROJECTPROJECTRESOURCE = "FETCH_PROJECTPROJECTRESOURCE";
export const DELETE_PROJECTPROJECTRESOURCE = "DELETE_PROJECTPROJECTRESOURCE";
export const EDIT_PROJECTPROJECTRESOURCE = "EDIT_PROJECTPROJECTRESOURCE";

// for projects on projects budgeting
export const CREATE_PROJECTPROJECTBUDGETING = "CREATE_PROJECTPROJECTBUDGETING";
export const FETCH_PROJECTPROJECTBUDGETINGS = "FETCH_PROJECTPROJECTBUDGETINGS";
export const FETCH_PROJECTPROJECTBUDGETING = "FETCH_PROJECTPROJECTBUDGETING";
export const DELETE_PROJECTPROJECTBUDGETING = "DELETE_PROJECTPROJECTBUDGETING";
export const EDIT_PROJECTPROJECTBUDGETING = "EDIT_PROJECTPROJECTBUDGETING";

// for projects on projects planning tasks
export const CREATE_PROJECTPLANNINGTASK = "CREATE_PROJECTPLANNINGTASK";
export const FETCH_PROJECTPLANNINGTASKS = "FETCH_PROJECTPLANNINGTASKS";
export const FETCH_PROJECTPLANNINGTASK = "FETCH_PROJECTPLANNINGTASK";
export const DELETE_PROJECTPLANNINGTASK = "DELETE_PROJECTPLANNINGTASK";
export const EDIT_PROJECTPLANNINGTASK = "EDIT_PROJECTPLANNINGTASK";

// for projects on projects planning activities
export const CREATE_PROJECTPLANNINGACTIVITY = "CREATE_PROJECTPLANNINGACTIVITY";
export const FETCH_PROJECTPLANNINGACTIVITIES =
  "FETCH_PROJECTPLANNINGACTIVITIES";
export const FETCH_PROJECTPLANNINGACTIVITY = "FETCH_PROJECTPLANNINGACTIVITY";
export const DELETE_PROJECTPLANNINGACTIVITY = "DELETE_PROJECTPLANNINGACTIVITY";
export const EDIT_PROJECTPLANNINGACTIVITY = "EDIT_PROJECTPLANNINGACTIVITY";

// for projects on projects planning scheduling
export const CREATE_PROJECTPLANNINGSCHEDULING =
  "CREATE_PROJECTPLANNINGSCHEDULING";
export const FETCH_PROJECTPLANNINGSCHEDULINGS =
  "FETCH_PROJECTPLANNINGSCHEDULINGs";
export const FETCH_PROJECTPLANNINGSCHEDULING =
  "FETCH_PROJECTPLANNINGSCHEDULING";
export const DELETE_PROJECTPLANNINGSCHEDULING =
  "DELETE_PROJECTPLANNINGSCHEDULING";
export const EDIT_PROJECTPLANNINGSCHEDULING = "EDIT_PROJECTPLANNINGSCHEDULING";

// for projects on projects execution activities
export const CREATE_PROJECTEXECUTIONACTIVITY =
  "CREATE_PROJECTEXECUTIONACTIVITY";
export const FETCH_PROJECTEXECUTIONACTIVITIES =
  "FETCH_PROJECTEXECUTIONACTIVITIES";
export const FETCH_PROJECTEXECUTIONACTIVITY = "FETCH_PROJECTEXECUTIONACTIVITY";
export const DELETE_PROJECTEXECUTIONACTIVITY =
  "DELETE_PROJECTEXECUTIONACTIVITY";
export const EDIT_PROJECTEXECUTIONACTIVITY = "EDIT_PROJECTEXECUTIONACTIVITY";

// for projects on projects planning steps
export const CREATE_PROJECTPLANNINGSTEP = "CREATE_PROJECTPLANNINGSTEP";
export const FETCH_PROJECTPLANNINGSTEPS = "FETCH_PROJECTPLANNINGSTEPS";
export const FETCH_PROJECTPLANNINGSTEP = "FETCH_PROJECTPLANNINGSTEP";
export const DELETE_PROJECTPLANNINGSTEP = "DELETE_PROJECTPLANNINGSTEP";
export const EDIT_PROJECTPLANNINGSTEP = "EDIT_PROJECTPLANNINGSTEP";

// for projects on projects planning sequencing
export const CREATE_PROJECTPLANNINGSEQUENCING =
  "CREATE_PROJECTPLANNINGSEQUENCING";
export const FETCH_PROJECTPLANNINGSEQUENCINGS =
  "FETCH_PROJECTPLANNINGSEQUENCINGS";
export const FETCH_PROJECTPLANNINGSEQUENCING =
  "FETCH_PROJECTPLANNINGSEQUENCING";
export const DELETE_PROJECTPLANNINGSEQUENCING =
  "DELETE_PROJECTPLANNINGSEQUENCING";
export const EDIT_PROJECTPLANNINGSEQUENCING = "EDIT_PROJECTPLANNINGSEQUENCING";

// for projects on projects monitoring task
export const CREATE_PROJECTMONITORINGTASK = "CREATE_PROJECTMONITORINGTASK";
export const FETCH_PROJECTMONITORINGTASKS = "FETCH_PROJECTMONITORINGTASKS";
export const FETCH_PROJECTMONITORINGTASK = "FETCH_PROJECTMONITORINGTASK";
export const DELETE_PROJECTMONITORINGTASK = "DELETE_PROJECTMONITORINGTASK";
export const EDIT_PROJECTMONITORINGTASK = "EDIT_PROJECTMONITORINGTASK";

// for projects on projects monitoring activities
export const CREATE_PROJECTMONITORINGACTIVITY =
  "CREATE_PROJECTMONITORINGACTIVITY";
export const FETCH_PROJECTMONITORINGACTIVITIES =
  "FETCH_PROJECTMONITORINGACTIVITIES";
export const FETCH_PROJECTMONITORINGACTIVITY =
  "FETCH_PROJECTMONITORINGACTIVITY";
export const DELETE_PROJECTMONITORINGACTIVITY =
  "DELETE_PROJECTMONITORINGACTIVITY";
export const EDIT_PROJECTMONITORINGACTIVITY = "EDIT_PROJECTMONITORINGACTIVITY";

// for projects on projects closure
export const CREATE_PROJECTCLOSURE = "CREATE_PROJECTCLOSURE";
export const FETCH_PROJECTCLOSURES = "FETCH_PROJECTCLOSURES";
export const FETCH_PROJECTCLOSURE = "FETCH_PROJECTCLOSURE";
export const DELETE_PROJECTCLOSURE = "DELETE_PROJECTCLOSURE";
export const EDIT_PROJECTCLOSURE = "EDIT_PROJECTCLOSURE";

// for crm contacts
export const CREATE_CONTACT = "CREATE_CONTACT";
export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const FETCH_CONTACT = "FETCH_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";

// for crm partners
export const CREATE_PARTNER = "CREATE_PARTNER";
export const FETCH_PARTNERS = "FETCH_PARTNERS";
export const FETCH_PARTNER = "FETCH_PARTNER";
export const DELETE_PARTNER = "DELETE_PARTNER";
export const EDIT_PARTNER = "EDIT_PARTNER";

// for crm suppliers
export const CREATE_SUPPLIER = "CREATE_SUPPLIER";
export const FETCH_SUPPLIERS = "FETCH_SUPPLIERS";
export const FETCH_SUPPLIER = "FETCH_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const EDIT_SUPPLIER = "EDIT_SUPPLIER";

// for crm customers
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";

// for sales products
export const CREATE_SALESPRODUCT = "CREATE_SALESPRODUCT";
export const FETCH_SALESPRODUCTS = "FETCH_SALESPRODUCTS";
export const FETCH_SALESPRODUCT = "FETCH_SALESPRODUCT";
export const DELETE_SALESPRODUCT = "DELETE_SALESPRODUCT";
export const EDIT_SALESPRODUCT = "EDIT_SALESPRODUCT";

// for sales team
export const CREATE_SALESTEAM = "CREATE_SALESTEAM";
export const FETCH_SALESTEAMS = "FETCH_SALESTEAMS";
export const FETCH_SALESTEAM = "FETCH_SALESTEAM";
export const DELETE_SALESTEAM = "DELETE_SALESTEAM";
export const EDIT_SALESTEAM = "EDIT_SALESTEAM";

// for sales team members
export const CREATE_SALESTEAMMEMBER = "CREATE_SALESTEAMMEMBER";
export const FETCH_SALESTEAMMEMBERS = "FETCH_SALESTEAMMEMBERS";
export const FETCH_SALESTEAMMEMBER = "FETCH_SALESTEAMMEMBER";
export const DELETE_SALESTEAMMEMBER = "DELETE_SALESTEAMMEMBER";
export const EDIT_SALESTEAMMEMBER = "EDIT_SALESTEAMMEMBER";

// for sales team members
export const CREATE_SALESTASK = "CREATE_SALESTASK";
export const FETCH_SALESTASKS = "FETCH_SALESTASKS";
export const FETCH_SALESTASK = "FETCH_SALESTASK";
export const DELETE_SALESTASK = "DELETE_SALESTASK";
export const EDIT_SALESTASK = "EDIT_SALESTASK";

// for sales sales
export const CREATE_SALESSALE = "CREATE_SALESSALE";
export const FETCH_SALESSALES = "FETCH_SALESSALES";
export const FETCH_SALESSALE = "FETCH_SALESSALE";
export const DELETE_SALESSALE = "DELETE_SALESSALE";
export const EDIT_SALESSALE = "EDIT_SALESSALE";

// for sales invoice
export const CREATE_SALESINVOICE = "CREATE_SALESINVOICE";
export const FETCH_SALESINVOICES = "FETCH_SALESINVOICES";
export const FETCH_SALESINVOICE = "FETCH_SALESINVOICE";
export const DELETE_SALESINVOICE = "DELETE_SALESINVOICE";
export const EDIT_SALESINVOICE = "EDIT_SALESINVOICE";

// for sales account
export const CREATE_SALESACCOUNT = "CREATE_SALESACCOUNT";
export const FETCH_SALESACCOUNTS = "FETCH_SALESACCOUNTS";
export const FETCH_SALESACCOUNT = "FETCH_SALESACCOUNT";
export const DELETE_SALESACCOUNT = "DELETE_SALESACCOUNT";
export const EDIT_SALESACCOUNT = "EDIT_SALESACCOUNT";

// for HR utility unit / units
export const CREATE_HRUNIT = "CREATE_HRUNIT";
export const FETCH_HRUNITS = "FETCH_HRUNITS";
export const FETCH_HRUNIT = "FETCH_HRUNIT";
export const DELETE_HRUNIT = "DELETE_HRUNIT";
export const EDIT_HRUNIT = "EDIT_HRUNIT";

// for HR utility / department
export const CREATE_HRDEPARTMENT = "CREATE_HRDEPARTMENT";
export const FETCH_HRDEPARTMENTS = "FETCH_HRDEPARTMENTS";
export const FETCH_HRDEPARTMENT = "FETCH_HRDEPARTMENT";
export const DELETE_HRDEPARTMENT = "DELETE_HRDEPARTMENT";
export const EDIT_HRDEPARTMENT = "EDIT_HRDEPARTMENT";

// for HR utility / group
export const CREATE_HRGROUP = "CREATE_HRGROUP";
export const FETCH_HRGROUPS = "FETCH_HRGROUPS";
export const FETCH_HRGROUP = "FETCH_HRGROUP";
export const DELETE_HRGROUP = "DELETE_HRGROUP";
export const EDIT_HRGROUP = "EDIT_HRGROUP";

// for HR utility / division
export const CREATE_HRDIVISION = "CREATE_HRDIVISION";
export const FETCH_HRDIVISIONS = "FETCH_HRDIVISIONS";
export const FETCH_HRDIVISION = "FETCH_HRDIVISION";
export const DELETE_HRDIVISION = "DELETE_HRDIVISION";
export const EDIT_HRDIVISION = "EDIT_HRDIVISION";

// for HR utility / division
export const CREATE_HRDESIGNATION = "CREATE_HRDESIGNATION";
export const FETCH_HRDESIGNATIONS = "FETCH_HRDESIGNATIONS";
export const FETCH_HRDESIGNATION = "FETCH_HRDESIGNATION";
export const DELETE_HRDESIGNATION = "DELETE_HRDESIGNATION";
export const EDIT_HRDESIGNATION = "EDIT_HRDESIGNATION";

// for HR utility / kpi session
export const CREATE_HRKPISESSION = "CREATE_HRKPISESSION";
export const FETCH_HRKPISESSIONS = "FETCH_HRKPISESSIONS";
export const FETCH_HRKPISESSION = "FETCH_HRKPISESSION";
export const DELETE_HRKPISESSION = "DELETE_HRKPISESSION";
export const EDIT_HRKPISESSION = "EDIT_HRKPISESSION";

// for HR utility / appraisal season
export const CREATE_HRAPPRAISALSEASON = "CREATE_HRAPPRAISALSEASON";
export const FETCH_HRAPPRAISALSEASONS = "FETCH_HRAPPRAISALSEASONS";
export const FETCH_HRAPPRAISALSEASON = "FETCH_HRAPPRAISALSEASON";
export const DELETE_HRAPPRAISALSEASON = "DELETE_HRAPPRAISALSEASON";
export const EDIT_HRAPPRAISALSEASON = "EDIT_HRAPPRAISALSEASON";

// for HR roles
export const CREATE_HRROLE = "CREATE_HRROLE";
export const FETCH_HRROLES = "FETCH_HRROLES";
export const FETCH_HRROLE = "FETCH_HRROLE";
export const DELETE_HRROLE = "DELETE_HRROLE";
export const EDIT_HRROLE = "EDIT_HRROLE";

// for HR
export const CREATE_HRJOBDESCRIPTION = "CREATE_HRJOBDESCRIPTION";
export const FETCH_HRJOBDESCRIPTIONS = "FETCH_HRJOBDESCRIPTIONS";
export const FETCH_HRJOBDESCRIPTION = "FETCH_HRJOBDESCRIPTION";
export const DELETE_HRJOBDESCRIPTION = "DELETE_HRJOBDESCRIPTION";
export const EDIT_HRJOBDESCRIPTION = "EDIT_HRJOBDESCRIPTION";

// for HR
export const CREATE_HRPLANNINGSKILLSET = "CREATE_HRPLANNINGSKILLSET";
export const FETCH_HRPLANNINGSKILLSETS = "FETCH_HRPLANNINGSKILLSETS";
export const FETCH_HRPLANNINGSKILLSET = "FETCH_HRPLANNINGSKILLSET";
export const DELETE_HRPLANNINGSKILLSET = "DELETE_HRPLANNINGSKILLSET";
export const EDIT_HRPLANNINGSKILLSET = "EDIT_HRPLANNINGSKILLSET";

//Hr recruitment/initiation
export const CREATE_HRRECRUITMENTINITIATION = "CREATE_HRRECRUITMENTINITIATION";
export const FETCH_HRRECRUITMENTINITIATIONS = "FETCH_HRRECRUITMENTINITIATIONS";
export const FETCH_HRRECRUITMENTINITIATION = "FETCH_HRRECRUITMENTINITIATION";
export const DELETE_HRRECRUITMENTINITIATION = "DELETE_HRRECRUITMENTINITIATION";
export const EDIT_HRRECRUITMENTINITIATION = "EDIT_HRRECRUITMENTINITIATION";

//Hr recruitment/interviews
export const CREATE_HRRECRUITMENTINTERVIEW = "CREATE_HRRECRUITMENTINTERVIEW";
export const FETCH_HRRECRUITMENTINTERVIEWS = "FETCH_HRRECRUITMENTINTERVIEWS";
export const FETCH_HRRECRUITMENTINTERVIEW = "FETCH_HRRECRUITMENTINTERVIEW";
export const DELETE_HRRECRUITMENTINTERVIEW = "DELETE_HRRECRUITMENTINTERVIEW";
export const EDIT_HRRECRUITMENTINTERVIEW = "EDIT_HRRECRUITMENTINTERVIEW";

//Hr recruitment/selections
export const CREATE_HRRECRUITMENTSELECTION = "CREATE_HRRECRUITMENTSELECTION";
export const FETCH_HRRECRUITMENTSELECTIONS = "FETCH_HRRECRUITMENTSELECTIONS";
export const FETCH_HRRECRUITMENTSELECTION = "FETCH_HRRECRUITMENTSELECTION";
export const DELETE_HRRECRUITMENTSELECTION = "DELETE_HRRECRUITMENTSELECTION";
export const EDIT_HRRECRUITMENTSELECTION = "EDIT_HRRECRUITMENTSELECTION";

//Hr recruitment/onboarding
export const CREATE_HRRECRUITMENTONBOARD = "CREATE_HRRECRUITMENTONBOARD";
export const FETCH_HRRECRUITMENTONBOARDS = "FETCH_HRRECRUITMENTONBOARDS";
export const FETCH_HRRECRUITMENTONBOARD = "FETCH_HRRECRUITMENTONBOARD";
export const DELETE_HRRECRUITMENTONBOARD = "DELETE_HRRECRUITMENTONBOARD";
export const EDIT_HRRECRUITMENTONBOARD = "EDIT_HRRECRUITMENTONBOARD";

//Hr recruitment/placement
export const CREATE_HRRECRUITMENTPLACEMENT = "CREATE_HRRECRUITMENTPLACEMENT";
export const FETCH_HRRECRUITMENTPLACEMENTS = "FETCH_HRRECRUITMENTPLACEMENTS";
export const FETCH_HRRECRUITMENTPLACEMENT = "FETCH_HRRECRUITMENTPLACEMENT";
export const DELETE_HRRECRUITMENTPLACEMENT = "DELETE_HRRECRUITMENTPLACEMENT";
export const EDIT_HRRECRUITMENTPLACEMENT = "EDIT_HRRECRUITMENTPLACEMENT";

//Hr compensation/salary
export const CREATE_HRCOMPENSATIONSALARY = "CREATE_HRCOMPENSATIONSALARY";
export const FETCH_HRCOMPENSATIONSALARYS = "FETCH_HRCOMPENSATIONSALARYS";
export const FETCH_HRCOMPENSATIONSALARY = "FETCH_HRCOMPENSATIONSALARY";
export const DELETE_HRCOMPENSATIONSALARY = "DELETE_HRCOMPENSATIONSALARY";
export const EDIT_HRCOMPENSATIONSALARY = "EDIT_HRCOMPENSATIONSALARY";

//Hr compensation/bonuses
export const CREATE_HRCOMPENSATIONBONUS = "CREATE_HRCOMPENSATIONBONUS";
export const FETCH_HRCOMPENSATIONBONUSES = "FETCH_HRCOMPENSATIONBONUSES";
export const FETCH_HRCOMPENSATIONBONUS = "FETCH_HRCOMPENSATIONBONUS";
export const DELETE_HRCOMPENSATIONBONUS = "DELETE_HRCOMPENSATIONBONUS";
export const EDIT_HRCOMPENSATIONBONUS = "EDIT_HRCOMPENSATIONBONUS";

//Hr compensation/leave allowance
export const CREATE_HRCOMPENSATIONLEAVEALLOWANCE =
  "CREATE_HRCOMPENSATIONLEAVEALLOWANCE";
export const FETCH_HRCOMPENSATIONLEAVEALLOWANCES =
  "FETCH_HRCOMPENSATIONLEAVEALLOWANCES";
export const FETCH_HRCOMPENSATIONLEAVEALLOWANCE =
  "FETCH_HRCOMPENSATIONLEAVEALLOWANCE";
export const DELETE_HRCOMPENSATIONLEAVEALLOWANCE =
  "DELETE_HRCOMPENSATIONLEAVEALLOWANCE";
export const EDIT_HRCOMPENSATIONLEAVEALLOWANCE =
  "EDIT_HRCOMPENSATIONLEAVEALLOWANCE";

//Hr compensation/overtimes
export const CREATE_HRCOMPENSATIONOVERTIME = "CREATE_HRCOMPENSATIONOVERTIME";
export const FETCH_HRCOMPENSATIONOVERTIMES = "FETCH_HRCOMPENSATIONOVERTIMES";
export const FETCH_HRCOMPENSATIONOVERTIME = "FETCH_HRCOMPENSATIONOVERTIME";
export const DELETE_HRCOMPENSATIONOVERTIME = "DELETE_HRCOMPENSATIONOVERTIME";
export const EDIT_HRCOMPENSATIONOVERTIME = "EDIT_HRCOMPENSATIONOVERTIME";

//Hr compensation/staff loans
export const CREATE_HRCOMPENSATIONSTAFFLOAN = "CREATE_HRCOMPENSATIONSTAFFLOAN";
export const FETCH_HRCOMPENSATIONSTAFFLOANS = "FETCH_HRCOMPENSATIONSTAFFLOANS";
export const FETCH_HRCOMPENSATIONSTAFFLOAN = "FETCH_HRCOMPENSATIONSTAFFLOAN";
export const DELETE_HRCOMPENSATIONSTAFFLOAN = "DELETE_HRCOMPENSATIONSTAFFLOAN";
export const EDIT_HRCOMPENSATIONSTAFFLOAN = "EDIT_HRCOMPENSATIONSTAFFLOAN";

//Hr compensation/salary advance
export const CREATE_HRCOMPENSATIONSALARYADVANCE =
  "CREATE_HRCOMPENSATIONSALARYADVANCE";
export const FETCH_HRCOMPENSATIONSALARYADVANCES =
  "FETCH_HRCOMPENSATIONSALARYADVANCES";
export const FETCH_HRCOMPENSATIONSALARYADVANCE =
  "FETCH_HRCOMPENSATIONSALARYADVANCE";
export const DELETE_HRCOMPENSATIONSALARYADVANCE =
  "DELETE_HRCOMPENSATIONSALARYADVANCE";
export const EDIT_HRCOMPENSATIONSALARYADVANCE =
  "EDIT_HRCOMPENSATIONSALARYADVANCE";

//Hr compensation/certificate refund
export const CREATE_HRCOMPENSATIONCERTIFICATEREFUND =
  "CREATE_HRCOMPENSATIONCERTIFICATEREFUND";
export const FETCH_HRCOMPENSATIONCERTIFICATEREFUNDS =
  "FETCH_HRCOMPENSATIONCERTIFICATEREFUNDS";
export const FETCH_HRCOMPENSATIONCERTIFICATEREFUND =
  "FETCH_HRCOMPENSATIONCERTIFICATEREFUND";
export const DELETE_HRCOMPENSATIONCERTIFICATEREFUND =
  "DELETE_HRCOMPENSATIONCERTIFICATEREFUND";
export const EDIT_HRCOMPENSATIONCERTIFICATEREFUND =
  "EDIT_HRCOMPENSATIONCERTIFICATEREFUND";

//Hr leave/leave
export const CREATE_HRLEAVELEAVE = "CREATE_HRLEAVELEAVE";
export const FETCH_HRLEAVELEAVES = "FETCH_HRLEAVELEAVES";
export const FETCH_HRLEAVELEAVE = "FETCH_HRLEAVELEAVE";
export const DELETE_HRLEAVELEAVE = "DELETE_HRLEAVELEAVE";
export const EDIT_HRLEAVELEAVE = "EDIT_HRLEAVELEAVE";

//Hr exit/exit
export const CREATE_HREXITEXIT = "CREATE_HREXITEXIT";
export const FETCH_HREXITEXITS = "FETCH_HREXITEXITS";
export const FETCH_HREXITEXIT = "FETCH_HREXITEXIT";
export const DELETE_HREXITEXIT = "DELETE_HREXITEXIT";
export const EDIT_HREXITEXIT = "EDIT_HREXITEXIT";

//Hr exit/Clearance
export const CREATE_HREXITCLEARANCE = "CREATE_HREXITCLEARANCE";
export const FETCH_HREXITCLEARANCES = "FETCH_HREXITCLEARANCES";
export const FETCH_HREXITCLEARANCE = "FETCH_HREXITCLEARANCE";
export const DELETE_HREXITCLEARANCE = "DELETE_HREXITCLEARANCE";
export const EDIT_HREXITCLEARANCE = "EDIT_HREXITCLEARANCE";

//Hr performance/appraisal
export const CREATE_HRPERFORMANCEAPPRAISAL = "CREATE_HRPERFORMANCEAPPRAISAL";
export const FETCH_HRPERFORMANCEAPPRAISALS = "FETCH_HRPERFORMANCEAPPRAISALS";
export const FETCH_HRPERFORMANCEAPPRAISAL = "FETCH_HRPERFORMANCEAPPRAISAL";
export const DELETE_HRPERFORMANCEAPPRAISAL = "DELETE_HRPERFORMANCEAPPRAISAL";
export const EDIT_HRPERFORMANCEAPPRAISAL = "EDIT_HRPERFORMANCEAPPRAISAL";

//Hr performance/performance
export const CREATE_HRPERFORMANCEPERFORMANCE =
  "CREATE_HRPERFORMANCEPERFORMANCE";
export const FETCH_HRPERFORMANCEPERFORMANCES =
  "FETCH_HRPERFORMANCEPERFORMANCES";
export const FETCH_HRPERFORMANCEPERFORMANCE = "FETCH_HRPERFORMANCEPERFORMANCE";
export const DELETE_HRPERFORMANCEPERFORMANCE =
  "DELETE_HRPERFORMANCEPERFORMANCE";
export const EDIT_HRPERFORMANCEPERFORMANCE = "EDIT_HRPERFORMANCEPERFORMANCE";

//Hr self service/leave
export const CREATE_HRSELFSERVICELEAVE = "CREATE_HRSELFSERVICELEAVE";
export const FETCH_HRSELFSERVICELEAVES = "FETCH_HRSELFSERVICELEAVES";
export const FETCH_HRSELFSERVICELEAVE = "FETCH_HRSELFSERVICELEAVE";
export const DELETE_HRSELFSERVICELEAVE = "DELETE_HRSELFSERVICELEAVE";
export const EDIT_HRSELFSERVICELEAVE = "EDIT_HRSELFSERVICELEAVE";

//Hr self service/staff loans
export const CREATE_HRSELFSERVICESTAFFLOAN = "CREATE_HRSELFSERVICESTAFFLOAN";
export const FETCH_HRSELFSERVICESTAFFLOANS = "FETCH_HRSELFSERVICESTAFFLOANS";
export const FETCH_HRSELFSERVICESTAFFLOAN = "FETCH_HRSELFSERVICESTAFFLOAN";
export const DELETE_HRSELFSERVICESTAFFLOAN = "DELETE_HRSELFSERVICESTAFFLOAN";
export const EDIT_HRSELFSERVICESTAFFLOAN = "EDIT_HRSELFSERVICESTAFFLOAN";

//Hr self service/certificate refund
export const CREATE_HRSELFSERVICECERTREFUND = "CREATE_HRSELFSERVICECERTREFUND";
export const FETCH_HRSELFSERVICECERTREFUNDS = "FETCH_HRSELFSERVICECERTREFUNDS";
export const FETCH_HRSELFSERVICECERTREFUND = "FETCH_HRSELFSERVICECERTREFUND";
export const DELETE_HRSELFSERVICECERTREFUND = "DELETE_HRSELFSERVICECERTREFUND";
export const EDIT_HRSELFSERVICECERTREFUND = "EDIT_HRSELFSERVICECERTREFUND";

//Hr self service/exit
export const CREATE_HRSELFSERVICEEXIT = "CREATE_HRSELFSERVICEEXIT";
export const FETCH_HRSELFSERVICEEXITS = "FETCH_HRSELFSERVICEEXITS";
export const FETCH_HRSELFSERVICEEXIT = "FETCH_HRSELFSERVICEEXIT";
export const DELETE_HRSELFSERVICEEXIT = "DELETE_HRSELFSERVICEEXIT";
export const EDIT_HRSELFSERVICEEXIT = "EDIT_HRSELFSERVICEEXIT";

//Hr self service/overtimes
export const CREATE_HRSELFSERVICEOVERTIME = "CREATE_HRSELFSERVICEOVERTIME";
export const FETCH_HRSELFSERVICEOVERTIMES = "FETCH_HRSELFSERVICEOVERTIMES";
export const FETCH_HRSELFSERVICEOVERTIME = "FETCH_HRSELFSERVICEOVERTIME";
export const DELETE_HRSELFSERVICEOVERTIME = "DELETE_HRSELFSERVICEOVERTIME";
export const EDIT_HRSELFSERVICEOVERTIME = "EDIT_HRSELFSERVICEOVERTIME";

//Hr self service/salary advance
export const CREATE_HRSELFSERVICESALARYADVANCE =
  "CREATE_HRSELFSERVICESALARYADVANCE";
export const FETCH_HRSELFSERVICESALARYADVANCES =
  "FETCH_HRSELFSERVICESALARYADVANCES";
export const FETCH_HRSELFSERVICESALARYADVANCE =
  "FETCH_HRSELFSERVICESALARYADVANCE";
export const DELETE_HRSELFSERVICESALARYADVANCE =
  "DELETE_HRSELFSERVICESALARYADVANCE";
export const EDIT_HRSELFSERVICESALARYADVANCE =
  "EDIT_HRSELFSERVICESALARYADVANCE";

//Hr self service/appraisal
export const CREATE_HRSELFSERVICEAPPRAISAL = "CREATE_HRSELFSERVICEAPPRAISAL";
export const FETCH_HRSELFSERVICEAPPRAISALS = "FETCH_HRSELFSERVICEAPPRAISALS";
export const FETCH_HRSELFSERVICEAPPRAISAL = "FETCH_HRSELFSERVICEAPPRAISAL";
export const DELETE_HRSELFSERVICEAPPRAISAL = "DELETE_HRSELFSERVICEAPPRAISAL";
export const EDIT_HRSELFSERVICEAPPRAISAL = "EDIT_HRSELFSERVICEAPPRAISAL";

//Hr self service/payslip
export const CREATE_HRSELFSERVICEPAYSLIP = "CREATE_HRSELFSERVICEPAYSLIP";
export const FETCH_HRSELFSERVICEPAYSLIPS = "FETCH_HRSELFSERVICEPAYSLIPS";
export const FETCH_HRSELFSERVICEPAYSLIP = "FETCH_HRSELFSERVICEPAYSLIP";
export const DELETE_HRSELFSERVICEPAYSLIP = "DELETE_HRSELFSERVICEPAYSLIP";
export const EDIT_HRSELFSERVICEPAYSLIP = "EDIT_HRSELFSERVICEPAYSLIP";
